### PR TITLE
Related #64 | Add TRANSLITERATION task in constants.py

### PR DESCRIPTION
**Pull request by akhdanfadh**
Related with #64 as I need to add a new task namely `TRANSLITERATION` with `t2t` schema.
I already made sure there is no other `"TR"` value in the Tasks class, though I'm not sure what it is for.

I have done implementing #64 dataloader, so it would be appreciated if this could be merged soon.

### CODE REVIEW

**Comment by sabilmakbar** [comment]
I'm testing this first and see whether this new schema could fit into the overall implementation.

**Comment by akhdanfadh** [comment]
There is no new schema added, I just add a task with existing `t2t` schema @sabilmakbar

**Comment by sabilmakbar** [comment]
Tested using one of the codebase of MT Dataloader w/ temp change to `Tasks.TRANSLITERATION`. LGTM, thanks @akhdanfadh!

**Review by sabilmakbar — APPROVED** [review]

**Comment by sabilmakbar** [comment]
Hi, let's wait for #127 PR merged first, then we can do on this one after the changes have been pulled to this PR too, since both PR have `constants.py` changed

**Review by holylovenia — APPROVED** [review]
LGTM!! Thanks for the new task, @akhdanfadh!! 🙏

**Pull request merged**
