### PR TITLE
Closes #308 | Implement dataloader for Multilabel Multiclass Sentiment and Emotion Dataset from Indonesian Mobile Application Review

### LINKED ISSUE #308: Create dataset loader for Multilabel Multiclass Sentiment and Emotion Dataset from Indonesian Mobile Application Review
Dataloader name: `id_sent_emo_mobile_apps/id_sent_emo_mobile_apps.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?id_sent_emo_mobile_apps

|     Dataset| id_sent_emo_mobile_apps |
|-------------|---|
| Description | This dataset contains manually annotated public reviews of mobile applications in Indonesia. Each review is given a sentiment label (positive, negative, neutral) and an emotion label (anger, sadness, fear, happiness, love, neutral). |
| Subsets | - |
| Languages | ind |
| Tasks | Sentiment Analysis, Emotion Classification |
| License | Creative Commons Attribution Non Commercial No Derivatives 4.0 (cc-by-nc-nd-4.0) |
| Homepage | https://github.com/Ricco48/Multilabel-Sentiment-and-Emotion-Dataset-from-Indonesian-Mobile-Application-Review/tree/CreateCodeForPaper |
| HF URL | - |
| Paper URL | https://www.sciencedirect.com/science/article/pii/S2352340923006662 |

### PR DESCRIPTION
**Pull request by elyanah-aco**
Closes #308.

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

### CODE REVIEW

**Comment by MJonibek** [comment]
@elyanah-aco Thank you for implementing this dataloader. Everything works. But I have a question: Maybe it is better just to leave id_sent_emo_mobile_apps_source , instead of dividing it into two subsets, because they are the same.

c.c. @SamuelCahyawijaya what is your opinion regarding it?

**Comment by elyanah-aco** [comment]
@MJonibek I split dataset into two subsets because its two tasks share the same schema with features referring to two different cols. Is it possible to implement this w/o using subsets?

**Review by MJonibek — CHANGES_REQUESTED** [review]

**Review by MJonibek — APPROVED** [review]
LGTM, lets wait @SamuelCahyawijaya

**Review by SamuelCahyawijaya — APPROVED** [review]
@elyanah-aco : thank you for the contribution and for also implementing the emotion recognition task (we only list the sentiment analysis task before, but I will add the emotion recognition to the metadata as well). LGTM!

**Pull request merged**
