### PR TITLE
Closes #163 | Add Bloom-Speech Dataloader

### LINKED ISSUE #163: Create dataset loader for Bloom-speech
Dataloader name: `bloom_speech/bloom_speech.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?bloom_speech

|     Dataset| bloom_speech |
|-------------|---|
| Description | This version of the Bloom Library data is developed specifically for the automatic speech recognition and speech-to-text tasks. It includes data from 56 languages across 18 language families. 8 languages are spoken in Southeast Asia |
| Subsets | bjn, bzi, ceb, ind, jra, kqr, mya, tgl |
| Languages | bjn, bzi, ceb, ind, jra, kqr, mya, tgl |
| Tasks | Speech-to-Text Translation, Text-To-Speech Synthesis |
| License | Other (other) |
| Homepage | https://huggingface.co/datasets/sil-ai/bloom-speech |
| HF URL | https://huggingface.co/datasets/sil-ai/bloom-speech |
| Paper URL | https://aclanthology.org/2022.emnlp-main.590 |

### PR DESCRIPTION
**Pull request by sabilmakbar**
Closes #163.

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

### CODE REVIEW

**Comment by sabilmakbar** [comment]
Adding the logs of test-cases upon all 8 languages:
[.log file](https://github.com/SEACrowd/seacrowd-datahub/files/13785624/test_log_bloom_speech.log)

**Review by jen-santoso — COMMENTED** [review]
Hi @sabilmakbar, 
there is a nit for line 33 (`abstract`) where `make check_file` marks this as too long (1070 > 250 characters). 
Other than that, tested and LGTM.

**Comment by sabilmakbar** [comment]
> Hi @sabilmakbar,
> there is a nit for line 33 (abstract) where make check_file marks this as too long (1070 > 250 characters).
> Other than that, tested and LGTM.

Thanks @jen-santoso, I was aware of it and commiting on that regardless. After re-considering it, I'm removing the abstract altogether from the `_CITATION` info

**Comment by ljvmiranda921** [comment]
Will review within the week!

**Review by jen-santoso — APPROVED** [review]
LGTM

**Review by ljvmiranda921 — APPROVED** [review]
LGTM thank you for the nice PR!

**Pull request merged**
