### PR TITLE
Closes #481 | Add Dataloader Aya Collection - Templated

### LINKED ISSUE #481: Create dataset loader for Aya Collection - Templated
Dataloader name: `aya_collection_templated/aya_collection_templated.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?aya_collection_templated

|     Dataset| aya_collection_templated |
|-------------|---|
| Description | The Aya Collection is a massive multilingual collection consisting of 513 million instances of prompts and completions covering a wide range of tasks. This dataset covers the templated prompts of the Aya Collection. |
| Subsets | NusaXSenti, Thai-POS-inst, SCB-MT-2020-prompt, Thai-USEmbassy-prompt, Thai-Wikitionary-inst, UNER-LLM-inst, X-CSQA-inst |
| Languages | ind, jav, sun, ace, ban, bbc, bjn, min, nij, tha, tgl, vie |
| Tasks | Chatbot |
| License | Apache license 2.0 (apache-2.0) |
| Homepage | https://huggingface.co/datasets/CohereForAI/aya_evaluation_suite |
| HF URL | - |
| Paper URL | https://arxiv.org/abs/2402.06619 |

### PR DESCRIPTION
**Pull request by muhammadravi251001**
**Title**: Add Dataloader Aya Collection - Templated

**First line PR Message**: Closes https://github.com/SEACrowd/seacrowd-datahub/issues/481

Notes:
- In this issue (https://github.com/SEACrowd/seacrowd-datahub/issues/481), it's written that exists Tagalog language (`tgl`); after I check on the official Hugging Face dataset [here](https://huggingface.co/datasets/CohereForAI/aya_collection) --> especially on UNER-LLM-inst dataset and X-CSQA-inst dataset, there is no `tgl` language.
- The split between `training`, `testing`, and `validation` are not perfectly structured, sometimes the SEA language only has `training`, sometimes only `testing`, and so on. So I initiate to move all of the language (SEA) to the `train` set to tidy up the dataset. Additionally, this is also an issue for `aya-dataset` before that was merged on https://github.com/SEACrowd/seacrowd-datahub/pull/457.

Test:
You can check this dataloader implementation by copy-pasting this command (to make a faster evaluation):
```
python -m tests.test_seacrowd seacrowd/sea_datasets/aya_collection_templated/aya_collection_templated.py --subset_id aya_collection_templated_ind
python -m tests.test_seacrowd seacrowd/sea_datasets/aya_collection_templated/aya_collection_templated.py --subset_id aya_collection_templated_jav
python -m tests.test_seacrowd seacrowd/sea_datasets/aya_collection_templated/aya_collection_templated.py --subset_id aya_collection_templated_sun
python -m tests.test_seacrowd seacrowd/sea_datasets/aya_collection_templated/aya_collection_templated.py --subset_id aya_collection_templated_ace
python -m tests.test_seacrowd seacrowd/sea_datasets/aya_collection_templated/aya_collection_templated.py --subset_id aya_collection_templated_ban
python -m tests.test_seacrowd seacrowd/sea_datasets/aya_collection_templated/aya_collection_templated.py --subset_id aya_collection_templated_bbc
python -m tests.test_seacrowd seacrowd/sea_datasets/aya_collection_templated/aya_collection_templated.py --subset_id aya_collection_templated_bjn
python -m tests.test_seacrowd seacrowd/sea_datasets/aya_collection_templated/aya_collection_templated.py --subset_id aya_collection_templated_min
python -m tests.test_seacrowd seacrowd/sea_datasets/aya_collection_templated/aya_collection_templated.py --subset_id aya_collection_templated_nij
python -m tests.test_seacrowd seacrowd/sea_datasets/aya_collection_templated/aya_collection_templated.py --subset_id aya_collection_templated_tha
python -m tests.test_seacrowd seacrowd/sea_datasets/aya_collection_templated/aya_collection_templated.py --subset_id aya_collection_templated_vie
```

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/{my_dataset}/{my_dataset}.py` (please use only lowercase and underscore for dataset folder naming, as mentioned in dataset issue) and its `__init__.py` within `{my_dataset}` folder.
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_LOCAL`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py` or `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py --subset_id {subset_name_without_source_or_seacrowd_suffix}`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

### CODE REVIEW

**Review by yongzx — APPROVED** [review]
Thank you @muhammadravi251001! The code looks good to me, and the unit tests run successfully on my end (appreciate the unit test code)

**Comment by muhammadravi251001** [comment]
> Thank you @muhammadravi251001! The code looks good to me, and the unit tests run successfully on my end (appreciate the unit test code)

Thanks for the approval, Sir!

**Review by luckysusanto — APPROVED** [review]
Everything looks good, manual test passed and code is clear and clean.
Thanks for the code ^^

**Comment by muhammadravi251001** [comment]
> Everything looks good, manual test passed and code is clear and clean.
> Thanks for the code ^^

Thanks for the approval, Lucky!

**Comment by yongzx** [comment]
Merging it since we all approved it. Thanks @muhammadravi251001

**Pull request merged**
