### PR TITLE
Closes #144 | Add OpenLID Dataloader

### LINKED ISSUE #144: Create dataset loader for OpenLID
Dataloader name: `openlid/openlid.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?openlid

|     Dataset| openlid |
|-------------|---|
| Description | This is an open dataset covering 201 languages, which are curated and audited manually to ensure high confidence in its data and language labels. 22 languages are native to Southeast Asia speakers. |
| Subsets | - |
| Languages | ace, ban, bjn, bug, ceb, ilo, ind, jav, kac, khm, lao, min, lus, mya, pag, shn, sun, tgl, tha, vie, war, zsm |
| Tasks | Language Identification |
| License | GNU General Public License v3.0 (gpl-3.0) |
| Homepage | https://github.com/laurieburchell/open-lid-dataset |
| HF URL | - |
| Paper URL | https://aclanthology.org/2023.acl-short.75 |

### PR DESCRIPTION
**Pull request by yana-xuyan**
Closes #144 

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

### CODE REVIEW

**Review by gentaiscool — APPROVED** [review]
lgtm.

**Comment by sabilmakbar** [comment]
Hi @yana-xuyan, mind removing non-dataloader code change in this PR and opening another PR for that (or perhaps pull the most recent config from `master` and see it if it has been implemented)?

Thanks!

**Comment by yana-xuyan** [comment]
Let me check this issue later this weekend :)

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Salsabil Maulana Akbar ***@***.***>
发送时间: Thursday, January 4, 2024 11:04:57 PM
收件人: SEACrowd/seacrowd-datahub ***@***.***>
抄送: Yan XU ***@***.***>; Mention ***@***.***>
主题: Re: [SEACrowd/seacrowd-datahub] Closes #144 | Add OpenLID Dataloader (PR #241)


Hi @yana-xuyan<https://github.com/yana-xuyan>, mind removing non-dataloader code change in this PR and opening another PR for that (or perhaps pull the most recent config from master and see it if it has been implemented)?

Thanks!

―

**Comment by yana-xuyan** [comment]
Hi, I have re-committed the dataloader. Please have a check when you're free. Many thanks!

**Review by SamuelCahyawijaya — APPROVED** [review]
Thank you for contributing, @yana-xuyan!! LGTM!

**Pull request merged**
