### PR TITLE
Closes #17 | Implement dataloader for Philippine Fake News Corpus

### LINKED ISSUE #17: Create dataset loader for Philippine Fake News Corpus
Dataloader name: `ph_fake_news_corpus/ph_fake_news_corpus.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?ph_fake_news_corpus

|     Dataset| ph_fake_news_corpus |
|-------------|---|
| Description | The Philippine Fake News Corpus consists of news headlines and content from various "credible" and "non-credible" national news outlets. "Credible" sources were national broadsheets available in the National Library of the Philippines, while "non-credible" sources were sources included in lists of websites with fake or unverified content provided by government and private institutions. |
| Subsets | - |
| Languages | eng |
| Tasks | Fact Checking |
| License | Unknown (unknown) |
| Homepage | https://github.com/aaroncarlfernandez/Philippine-Fake-News-Corpus |
| HF URL | - |
| Paper URL | https://dl.acm.org/doi/abs/10.1145/3326467.3326490 |

### PR DESCRIPTION
**Pull request by elyanah-aco**
Closes #17.

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

### CODE REVIEW

**Review by ljvmiranda921 — COMMENTED** [review]
Hi @elyanah-aco , thanks for this PR!
The tests are erroring out. I also noticed that there's no SEACrowd-specific config and schema?

**Comment by elyanah-aco** [comment]
@ljvmiranda921 

This dataset was tagged as `source-only`, running `tests.test_seacrowd_source_only` should work.

**Comment by ljvmiranda921** [comment]
Ah okay got it. I didn't look into the convo thread in the Issues. LGTM!

**Review by ljvmiranda921 — APPROVED** [review]

**Review by ryanignatius — APPROVED** [review]
Reviewed and tested, LGTM

**Pull request merged**
