### PR TITLE
Closes #24 | Add dataset loader for UIT-ViSD4SA

### LINKED ISSUE #24: Create dataset loader for UIT-ViSD4SA
Dataloader name: `uit_visd4sa/uit_visd4sa.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?uit_visd4sa

|     Dataset| uit_visd4sa |
|-------------|---|
| Description | A Vietnamese dataset consisting of 35,396 human-annotated spans on 11,122 feedback comments for evaluating span detection for aspect-based sentiment analysis for mobile e-commerce |
| Subsets | - |
| Languages | vie |
| Tasks | Aspect Based Sentiment Analysis |
| License | Unknown (unknown) |
| Homepage | https://github.com/kimkim00/UIT-ViSD4SA |
| HF URL | - |
| Paper URL | https://aclanthology.org/2021.paclic-1.34/ |

### PR DESCRIPTION
**Pull request by jen-santoso**
Please name your PR after the issue it closes. You can use the following line: "Closes #24 " where you replace the ISSUE-NUMBER with the one corresponding to your dataset.

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

### CODE REVIEW

**Comment by jen-santoso** [comment]
To reviewers:
I revised some of the implementations regarding the dataset loader for seacrowd.
This task is a span detection for aspect-based sentiment analysis.
Currently, the closest task is supposed to be `Tasks.ASPECT_BASED_SENTIMENT_ANALYSIS`. 
However, since there are aspects with contradictory labels in the same data and to preserve the span, I moved the task to `Tasks.COREFERENCE_RESOLUTION` and contain the information in schema `seacrowd_kb` instead of the schema `seacrowd_text_multi`.

Please let me know of the possible adjustments or any suggestions regarding the content.

**Comment by holylovenia** [comment]
Hi @jen-santoso, thanks for your contribution!! 🥳 Before the review, please let me throw a quick question to the other maintainers: I'll make a new task `Tasks.SPAN_BASED_ABSA` for this dataloader if you both agree @sabilmakbar @SamuelCahyawijaya.

**Comment by sabilmakbar** [comment]
Sounds perfect to me, @holylovenia! Thanks!

**Review by holylovenia — CHANGES_REQUESTED** [review]
Hi @SamuelCahyawijaya, thanks for the brilliant suggestion. @jen-santoso and I discussed the possibility of using the schema `seq_label` for this `Tasks.SPAN_BASED_ABSA` and agreed with your suggestion.

I have changed the schema-task mapping accordingly in the `master` branch and @jen-santoso will change the `kb` schema to `seq_label` for this dataloader implementation.

**Comment by jen-santoso** [comment]
@holylovenia @SamuelCahyawijaya done changing the schema to `seq_label`. Please check!

**Review by holylovenia — CHANGES_REQUESTED** [review]
Hi @jen-santoso, thanks for the dataloader! It works well. I have a minor request though, could you please provide the `_LANGUAGES` constant?

**Comment by jen-santoso** [comment]
@holylovenia updated

**Comment by holylovenia** [comment]
> @holylovenia updated

Ah sorry I wasn't clear before, array form please. 🙏

**Comment by jen-santoso** [comment]
> > @holylovenia updated
> 
> Ah sorry I wasn't clear before, array form please. 🙏

ok now in array form >.<

**Review by holylovenia — APPROVED** [review]
Thanks for your help, @jen-santoso!! Looks good to me~ Let's wait for @SamuelCahyawijaya's review before we proceed to merging.

**Review by SamuelCahyawijaya — APPROVED** [review]
@jen-santoso : thank you for updating the schema. LGTM!.

Based on our internal discussion, we decided to give +2 bonus points for this contribution.

**Pull request merged**
