### PR TITLE
Create Private Dataset Owner FAQ and Reviewer SOP

### PR DESCRIPTION
**Pull request by jcblaisecruz02**
Adds the following files for transparency in contacting private dataset owners:
* `PRIVATE.md` - FAQs for owners of private datasets contacted by SEACrowd moderators
* `REVIEWING.md` - FAQs, guidelines, and checklist for reviewers of public and private data.

### CODE REVIEW

**Review by holylovenia — CHANGES_REQUESTED** [review]
Hi @jcblaisecruz02, thanks for summarizing our FAQs to be in the github! Would you mind adding our dataloader reviewer SOP to the `REVIEWING.md` for completion?

**Comment by sabilmakbar** [comment]
Hi @holylovenia, In that case, may I add those SOPs of Dataloader to this new file? I also had comments on its wording to clarify the contents better since the POV is quite unclear on `REVIEWING.md` and we should use contributor/end-user POV rather than Mods POV

cc @jcblaisecruz02

**Comment by jcblaisecruz02** [comment]
@sabilmakbar sure that works! We can always give it another review after.

**Comment by holylovenia** [comment]
@sabilmakbar Sure, thanks in advance!! Please let me know if you need any help regarding this.

**Comment by holylovenia** [comment]
> Hi @jcblaisecruz02, thanks for summarizing our FAQs to be in the github! Would you mind adding our dataloader reviewer SOP to the `REVIEWING.md` for completion?

CMIIW, but I think we have to do this first before proceeding with edits, right? cc: @jcblaisecruz02 @sabilmakbar

**Comment by jcblaisecruz02** [comment]
> > Hi @jcblaisecruz02, thanks for summarizing our FAQs to be in the github! Would you mind adding our dataloader reviewer SOP to the `REVIEWING.md` for completion?
> 
> CMIIW, but I think we have to do this first before proceeding with edits, right? cc: @jcblaisecruz02 @sabilmakbar

@holylovenia yup. I'm waiting for @sabilmakbar to add the SOPs (as he mentioned) to the existing PR before we review and re-edit the doc.

**Comment by sabilmakbar** [comment]
Hi @jcblaisecruz02, @holylovenia, @SamuelCahyawijaya, apologies for delayed completion. I've added the PR on Dataloader SOP to Blaise's Repo first (so that his changes aren't overridden automatically with mine). After it has been merged to Blaise PR (which will be reflected in here automatically), we can proceed on reviewing this PR.

**Review by holylovenia — APPROVED** [review]
Got it, @sabilmakbar. I'll merge this PR then. Thanks and happy holidays~ ☃️

**Pull request merged**
