### PR TITLE
Closes #32 (High Prio) | Extend XL Sum Dataloaders to SEA Langs

### LINKED ISSUE #32: Create dataset loader for XL-Sum
Dataloader name: `xl_sum/xl_sum.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?xl_sum

|     Dataset| xl_sum |
|-------------|---|
| Description | XL-Sum, a comprehensive and diverse dataset comprising 1 million professionally annotated article-summary pairs from BBC, was extracted using a set of carefully designed heuristics. The dataset covers 44 languages ranging from low to high-resource, including 4 indigenous languages spoken in Southeast Asia region. |
| Subsets | XL-Sum Burmese, XL-Sum Indonesian, XL-Sum Thai, XL-Sum Vietnamnese |
| Languages | mya, ind, tha, vie |
| Tasks | Abstractive Summarization |
| License | Creative Commons Attribution Share Alike 4.0 (cc-by-sa-4.0) |
| Homepage | https://github.com/csebuetnlp/xl-sum |
| HF URL | https://huggingface.co/datasets/csebuetnlp/xlsum |
| Paper URL | https://aclanthology.org/2021.findings-acl.413/ |

### PR DESCRIPTION
**Pull request by sabilmakbar**
Please name your PR title and the first line of PR message after the issue it will close. You can use the following examples:

Closes #32 

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/{my_dataset}/{my_dataset}.py` (please use only lowercase and underscore for dataset folder naming, as mentioned in dataset issue) and its `__init__.py` within `{my_dataset}` folder.
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_LOCAL`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py` or `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py --subset_id {subset_name_without_source_or_seacrowd_suffix}`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

### CODE REVIEW

**Comment by sabilmakbar** [comment]
Test log on all available languages (all passed)
[test_xlsum.log](https://github.com/SEACrowd/seacrowd-datahub/files/14569931/test_xlsum.log)

**Comment by sabilmakbar** [comment]
> Hello, I got these errors when I tried to run the test, can you check?
> 
> Or is there any specific command do you use for the testing this code?

You may try using an optional args called `--subset_id` when testing it, it should be like this:
```bash
python -m tests.test_seacrowd seacrowd/sea_datasets/xl_sum/xl_sum.py --subset_id xl_sum_ind 
# it will test both xl_sum_ind_source and xl_sum_seacrowd_t2t
```

and you can do the similar for other langs (`mya`, `tha`, and `vie`)

**Review by faridlazuarda — APPROVED** [review]
Works fine in my tests, thank you!

**Review by SamuelCahyawijaya — APPROVED** [review]
@sabilmakbar : Thank you for your contribution! LGTM!

**Pull request merged**
