### PR TITLE
Relates #47 & #60 | Add 'OTHERS' in Licenses Config to cater custom Terms of Use

### PR DESCRIPTION
**Pull request by sabilmakbar**
### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Confirm that your changes in config passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.

Tested dataloader(s):
**ViText2SQL** (`vitext2sql/vitext2sql.py`)

### CODE REVIEW

**Comment by sabilmakbar** [comment]
Hi, this is the value for the `Licenses.OTHERS` in print statement:

```
THE DATA IS PROVIDED AS IS, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE DATA
OR THE USE OR OTHER DEALINGS IN THE DATA.
```

unlike the 1st commit LICENSE text value, which is indented, resulting in:
```
THE DATA IS PROVIDED AS IS, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
        INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
        IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
        WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE DATA
        OR THE USE OR OTHER DEALINGS IN THE DATA.
```

And when combined with Terms of Use (appended to this license string), with this statement (on `vitext2sql/vitext2sql.py`), will result in:
```python
>>> _LICENSE = f"""{Licenses.OTHERS.value} |
By downloading the ViText2SQL dataset, USER agrees:
1. to use ViText2SQL for research or educational purposes only.
2. to not distribute ViText2SQL or part of ViText2SQL in any original or modified form.
3. and to cite our EMNLP-2020 Findings paper above whenever ViText2SQL is employed to help produce published results."""
```

```THE DATA IS PROVIDED AS IS, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE DATA
OR THE USE OR OTHER DEALINGS IN THE DATA. |
By downloading the ViText2SQL dataset, USER agrees:
1. to use ViText2SQL for research or educational purposes only.
2. to not distribute ViText2SQL or part of ViText2SQL in any original or modified form.
3. and to cite our EMNLP-2020 Findings paper above whenever ViText2SQL is employed to help produce published results.```

**Review by holylovenia — CHANGES_REQUESTED** [review]
Hi @sabilmakbar, thanks for the PR. I'm currently away, but here's a quick feedback.

I think the expected output should be: `OTHERS | <custom_license>`.

For your example of ViText2SQL, it should be:
```
OTHERS | By downloading the ViText2SQL dataset, USER agrees:
1. to use ViText2SQL for research or educational purposes only.
2. to not distribute ViText2SQL or part of ViText2SQL in any original or modified form.
3. and to cite our EMNLP-2020 Findings paper above whenever ViText2SQL is employed to help produce published results.
```

This text you previously used:
```
THE DATA IS PROVIDED AS IS, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE DATA
OR THE USE OR OTHER DEALINGS IN THE DATA.
```
was supposed to be an example of the `<custom_license>`, sorry it wasn't clear.

**Comment by sabilmakbar** [comment]
oh yeah I misunderstood on this. The text that I assigned were a part of MIT License, the value should be `OTHER (Custom License)`

**Comment by sabilmakbar** [comment]
btw, the changes in other lines is due to the black formatting suggestions to this `constant.py`

**Comment by sabilmakbar** [comment]
btw, the changes in other lines are due to the black formatting suggestions to this constant.py

**Review by SamuelCahyawijaya — APPROVED** [review]
@sabilmakbar: Thank you for the update. LGTM!

**Review by holylovenia — APPROVED** [review]
LGTM! Thanks a lot for this prompt fix, @sabilmakbar!!

**Pull request merged**
