### PR TITLE
Closes #274 | Create OIL data loader

### LINKED ISSUE #274: Create dataset loader for OIL
Dataloader name: `oil/oil.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?oil

|     Dataset| oil |
|-------------|---|
| Description | The Online Indonesian Learning (OIL) dataset or corpus contains lessons from three Indonesian teachers who have posted content on YouTube. "Noisy" data, such as background noise, accented speech, task specific intonation/articulation, and frequent language mixing, was kept to provide realistic insight into the performance of ASR for the real-world task of converting teacher speech from YouTube into searchable text. Initial transcription was completed by the first author, who is an Indonesian-English bilingual, teacher, and linguist. |
| Subsets | - |
| Languages | ind, eng |
| Tasks | Automatic Speech Recognition |
| License | Creative Commons Attribution Non Commercial No Derivatives 4.0 (cc-by-nc-nd-4.0) |
| Homepage | https://huggingface.co/datasets/ZMaxwell-Smith/OIL |
| HF URL | https://huggingface.co/datasets/ZMaxwell-Smith/OIL |
| Paper URL | https://aclanthology.org/2023.fieldmatters-1.1.pdf |

### PR DESCRIPTION
**Pull request by Enliven26**
Closes [#274](https://github.com/SEACrowd/seacrowd-datahub/issues/274)

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [x] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

### CODE REVIEW

**Comment by MJonibek** [comment]
@Enliven26 I checked the dataloader. Works fine. However, I am not sure does it fulfill the purpose of SPEECH_RECOGNITION task. Because in this dataset every audio instead of the transcript has `"label"` (that is just `id`). Maybe we need to find where transcripts are stored (they are not on hugging face) or change the task. 

@jen-santoso What do you think?

**Comment by Enliven26** [comment]
Hi, may I know if the transcript is found? Thanks

**Comment by Enliven26** [comment]
@MJonibek

**Comment by jen-santoso** [comment]
> @Enliven26 I checked the dataloader. Works fine. However, I am not sure does it fulfill the purpose of SPEECH_RECOGNITION task. Because in this dataset every audio instead of the transcript has `"label"` (that is just `id`). Maybe we need to find where transcripts are stored (they are not on hugging face) or change the task.
> 
> @jen-santoso What do you think?

Sorry for the late notice. 
I think we should try to ask the authors about the transcripts (whether they are available or not), as it is weird to have ASR task dataset without any transcriptions for the audio.... 
@SamuelCahyawijaya @holylovenia @sabilmakbar what do you think?

In the meantime, I will review the dataloader using the available information.

**Review by jen-santoso — CHANGES_REQUESTED** [review]
Tested and runs well. One nit for `_CITATION` though, and in the meantime will consider again regarding the Tasks definition issue (or if the transcription is found)

**Comment by Enliven26** [comment]
Hi, changed the citation and added the init file. Is there any other necessary changes? Thanks

**Comment by jen-santoso** [comment]
@Enliven26 Thanks for the updates! 
we are still currently working on finding the transcripts.
the current changes LGTM, but we will need to inform you later depending on the circumstances with the transcripts.

**Comment by holylovenia** [comment]
> > @Enliven26 I checked the dataloader. Works fine. However, I am not sure does it fulfill the purpose of SPEECH_RECOGNITION task. Because in this dataset every audio instead of the transcript has `"label"` (that is just `id`). Maybe we need to find where transcripts are stored (they are not on hugging face) or change the task.
> > @jen-santoso What do you think?
> 
> Sorry for the late notice. I think we should try to ask the authors about the transcripts (whether they are available or not), as it is weird to have ASR task dataset without any transcriptions for the audio.... @SamuelCahyawijaya @holylovenia @sabilmakbar what do you think?
> 
> In the meantime, I will review the dataloader using the available information.

I agree with you both, @jen-santoso and @MJonibek. If there's no transcription, it'd be better to change the task.

**Comment by Enliven26** [comment]
May I know to which task it is best to change?

**Comment by holylovenia** [comment]
> May I know to which task it is best to change?

Good question. I tried asking the dataset owner about the transcriptions [here](https://huggingface.co/datasets/ZMaxwell-Smith/OIL/discussions/2). Could you please try to email her 3 days from now if she still hasn't responded, @Enliven26?

I don't think there's any `seacrowd` task we can use unless we get the transcription. Maybe we should just implement the `source` schema if we still can't get the transcriptions in the end. What do you think, @MJonibek @jen-santoso?

**Comment by Enliven26** [comment]
> > May I know to which task it is best to change?
> 
> Good question. I tried asking the dataset owner about the transcriptions [here](https://huggingface.co/datasets/ZMaxwell-Smith/OIL/discussions/2). Could you please try to email her 3 days from now if she still hasn't responded, @Enliven26?
> 
> I don't think there's any `seacrowd` task we can use unless we get the transcription. Maybe we should just implement the `source` schema if we still can't get the transcriptions in the end. What do you think, @MJonibek @jen-santoso?

May I know where I can find the email @holylovenia ? Thanks!

**Comment by holylovenia** [comment]
> > > May I know to which task it is best to change?
> > 
> > 
> > Good question. I tried asking the dataset owner about the transcriptions [here](https://huggingface.co/datasets/ZMaxwell-Smith/OIL/discussions/2). Could you please try to email her 3 days from now if she still hasn't responded, @Enliven26?
> > I don't think there's any `seacrowd` task we can use unless we get the transcription. Maybe we should just implement the `source` schema if we still can't get the transcriptions in the end. What do you think, @MJonibek @jen-santoso?
> 
> May I know where I can find the email @holylovenia ? Thanks!

Please try with this email: Zara.Maxwell-Smith@anu.edu.au
I got it from [this paper](https://aclanthology.org/2023.fieldmatters-1.1.pdf).

**Comment by jen-santoso** [comment]
> > May I know to which task it is best to change?
> 
> Good question. I tried asking the dataset owner about the transcriptions [here](https://huggingface.co/datasets/ZMaxwell-Smith/OIL/discussions/2). Could you please try to email her 3 days from now if she still hasn't responded, @Enliven26?
> 
> I don't think there's any `seacrowd` task we can use unless we get the transcription. Maybe we should just implement the `source` schema if we still can't get the transcriptions in the end. What do you think, @MJonibek @jen-santoso?

@holylovenia @MJonibek @Enliven26 
In the meantime, we should just implement the `source` schema only for this PR... 
Once we get the transcription, we can re-open (or create a new) issue. 
Please let us know your opinions.

**Comment by holylovenia** [comment]
> > > May I know to which task it is best to change?
> > 
> > 
> > Good question. I tried asking the dataset owner about the transcriptions [here](https://huggingface.co/datasets/ZMaxwell-Smith/OIL/discussions/2). Could you please try to email her 3 days from now if she still hasn't responded, @Enliven26?
> > I don't think there's any `seacrowd` task we can use unless we get the transcription. Maybe we should just implement the `source` schema if we still can't get the transcriptions in the end. What do you think, @MJonibek @jen-santoso?
> 
> @holylovenia @MJonibek @Enliven26 In the meantime, we should just implement the `source` schema only for this PR... Once we get the transcription, we can re-open (or create a new) issue. Please let us know your opinions.

Agreed. I added a `source-only` flag to the issue.

**Comment by Enliven26** [comment]
> > > > May I know to which task it is best to change?
> > > 
> > > 
> > > Good question. I tried asking the dataset owner about the transcriptions [here](https://huggingface.co/datasets/ZMaxwell-Smith/OIL/discussions/2). Could you please try to email her 3 days from now if she still hasn't responded, @Enliven26?
> > > I don't think there's any `seacrowd` task we can use unless we get the transcription. Maybe we should just implement the `source` schema if we still can't get the transcriptions in the end. What do you think, @MJonibek @jen-santoso?
> > 
> > 
> > @holylovenia @MJonibek @Enliven26 In the meantime, we should just implement the `source` schema only for this PR... Once we get the transcription, we can re-open (or create a new) issue. Please let us know your opinions.
> 
> Agreed. I added a `source-only` flag to the issue.

May I ask what should I do with the existing logic for the seacrowd schema? I tried removing seacrowd schema and leave only source schema but the unit test then raise a value error.

```raise ValueError(
ValueError: BuilderConfig 'oil_seacrowd_sptext' not found. Available: ['oil_source']
```

**Comment by Enliven26** [comment]
> > > > > May I know to which task it is best to change?
> > > > 
> > > > 
> > > > Good question. I tried asking the dataset owner about the transcriptions [here](https://huggingface.co/datasets/ZMaxwell-Smith/OIL/discussions/2). Could you please try to email her 3 days from now if she still hasn't responded, @Enliven26?
> > > > I don't think there's any `seacrowd` task we can use unless we get the transcription. Maybe we should just implement the `source` schema if we still can't get the transcriptions in the end. What do you think, @MJonibek @jen-santoso?
> > > 
> > > 
> > > @holylovenia @MJonibek @Enliven26 In the meantime, we should just implement the `source` schema only for this PR... Once we get the transcription, we can re-open (or create a new) issue. Please let us know your opinions.
> > 
> > 
> > Agreed. I added a `source-only` flag to the issue.
> 
> May I ask what should I do with the existing logic for the seacrowd schema @holylovenia ? I tried removing seacrowd schema and leave only source schema but the unit test then raise a value error.
> 
> ```
> ValueError: BuilderConfig 'oil_seacrowd_sptext' not found. Available: ['oil_source']
> ```

**Comment by Enliven26** [comment]
Please review my changes on removing seacrowd schema from the dataloader, thanks! @jen-santoso @MJonibek

**Review by MJonibek — APPROVED** [review]
Checked, LGTM! Thank you @Enliven26

**Review by jen-santoso — APPROVED** [review]

**Comment by jen-santoso** [comment]
Thank you for the update @Enliven26! LGTM, merging now...

**Pull request merged**
