### PR TITLE
Closes #29 | Add dataset loader for IJELID

### LINKED ISSUE #29: Create dataset loader for IJELID
Dataloader name: `ijelid/ijelid.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?ijelid

|     Dataset| ijelid |
|-------------|---|
| Description | This is a code-mixed Indonesian-Javanese-English dataset for token-level language identification. We named this dataset as IJELID (Indonesian-Javanese-English Language Identification). This dataset contains tweets that have been tokenized with the corresponding token and its language label. There are seven language labels in the dataset, namely: ID (Indonesian)JV (Javanese), EN (English),
MIX_ID_EN (mixed Indonesian-English), MIX_ID_JV (mixed Indonesian-Javanese), MIX_JV_EN (mixed Javanese-English), OTH (Other). |
| Subsets | - |
| Languages | ind, jav, eng |
| License | Creative Commons Attribution Non Commercial Share Alike 4.0 (cc-by-nc-sa-4.0) |
| Homepage | https://github.com/fathanick/Code-mixed-Indonesian-Javanese-English-Twitter-Data |
| HF URL | - |
| Paper URL | https://peerj.com/articles/cs-1312/ |

### PR DESCRIPTION
**Pull request by ljvmiranda921**
Closes #29 

Notes:
- IJELID is a token-level language identification task. I can't seem to find it in the supported tasks so I added a new one in this PR (https://github.com/SEACrowd/seacrowd-datahub/pull/45/commits/b472a1c53531f71f8091de41226c94e0ef3d002e)

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

### CODE REVIEW

**Review by ryanignatius — APPROVED** [review]
reviewed and tested,
LGTM

**Comment by yongzx** [comment]
The dataloader runs (`data = load_dataset("seacrowd/sea_datasets/ijelid/ijelid.py")`) without specifying config name. Is this intended?

**Comment by yongzx** [comment]
The dataloader runs (`data = load_dataset("seacrowd/sea_datasets/ijelid/ijelid.py")`) without needing to specify config name. Is this intended? @ljvmiranda921

**Comment by yongzx** [comment]
reviewed and tested as well.

**Review by yongzx — APPROVED** [review]

**Comment by ljvmiranda921** [comment]
Thanks for the reviews @ryanignatius and @yongzx !
As for the `load_dataset` question, it automatically loads the `DEFAULT_CONFIG_NAME` (in this case, `ijelid_souce`) when nothing's passed to the `name` parameter.

**Pull request merged**
