### PR TITLE
Adding New Citation for beaye_lexicon

### LINKED ISSUE #10: Create dataset loader for Beaye Lexicon
Dataloader name: `beaye_lexicon/beaye_lexicon.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?beaye_lexicon

|     Dataset| beaye_lexicon |
|-------------|---|
| Description | The Beaye Lexicon is a lexicon resource encompassing translations between Indonesian, English, and Beaye words. Developed through a collaborative effort involving two native Beaye speakers and evaluated by linguistic experts, this lexicon comprises 984 Beaye vocabularies. The creation of the Beaye Lexicon marks the inaugural effort in documenting the previously unrecorded Beaye language. |
| Subsets | lexicon |
| Languages | day |
| Tasks | Word lists |
| License | Apache license 2.0 (apache-2.0) |
| Homepage | https://github.com/joanitolopo/bhinneka-korpus/tree/main/lexicon |
| HF URL | - |
| Paper URL | https://drive.google.com/file/d/1AMWTvzhSyOf0kK89E8xbhsx34kwa-4dZ/view?usp=drivesdk |

### PR DESCRIPTION
**Pull request by joanitolopo**
Closes #10 
Adding New Citation for beaye_lexicon

### CODE REVIEW

**Review by holylovenia — CHANGES_REQUESTED** [review]
Hi @joanitolopo, could you please pull from the `master` branch and push only the necessary change (i.e., the citation change)?

In this state, it seems like the whole file was overwritten.

**Comment by holylovenia** [comment]
@joanitolopo Friendly reminder to update this PR.

**Comment by joanitolopo** [comment]
done kak @holylovenia

**Review by holylovenia — APPROVED** [review]
Thanks @joanitolopo!

**Pull request merged**
