### PR TITLE
Closes #13 | Create dataset loader for FSL-105

### LINKED ISSUE #13: Create dataset loader for FSL-105
Dataloader name: `fsl_105/fsl_105.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?fsl_105

|     Dataset| fsl_105 |
|-------------|---|
| Description | FSL-105 is a video dataset for 105 different Filipino Sign Language (FSL) signs. Each sign is categorized into one of 10 categories and is each represented by approximately 20 four-second video samples. Signs were performed by adult deaf FSL signers on a blank blue background and reviewed by an FSL expert. |
| Subsets | - |
| Languages | psp |
| Tasks | Image-to-Text Generation, Optical Character Recognition |
| License | Creative Commons Attribution 4.0 (cc-by-4.0) |
| Homepage | https://data.mendeley.com/datasets/48y2y99mb9/2 |
| HF URL | - |
| Paper URL | https://ieeexplore.ieee.org/document/10109284 |

### PR DESCRIPTION
**Pull request by IvanHalimP**
Please name your PR after the issue it closes. You can use the following line: "Closes #ISSUE-NUMBER" where you replace the ISSUE-NUMBER with the one corresponding to your dataset.
Closes #13 
### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

### CODE REVIEW

**Comment by IvanHalimP** [comment]
requires cv2 library. 
`pip3 install opencv-python`

**Comment by sabilmakbar** [comment]
Hi @IvanHalimP, thanks for the effort on this dataloader;

> requires cv2 library.
> pip3 install opencv-python
Regarding this dependency, may I know if:
1. The version of `opencv-python` that you use for this dataloader
2. The opt pkg is installed it along w/ SEACrowd Package Env
3. Doesn't conflict w/ existing reqs

Thanks in advance!

cc @holylovenia @SamuelCahyawijaya

**Comment by IvanHalimP** [comment]
> Hi @IvanHalimP, thanks for the effort on this dataloader.
> 
> > requires cv2 library.
> > pip3 install opencv-python
> 
> Regarding this dependency, may I know if the version of `opencv-python` that you use for this dataloader are:
> 
> 1. IInstalled along w/ SEACrowd Package Env
> 2. Doesn't conflict w/ existing reqs
> 
> Thanks in advance!
> 
> cc @holylovenia @SamuelCahyawijaya

Please find my answers below:

1. I don't find ```cv2``` library in the seacrowd's ```requirements.txt```.
2. As far as I can remember, I didn't face any issues back then when installing it into the ```env-seacrowd``` environment. I can be wrong though.

**Review by holylovenia — CHANGES_REQUESTED** [review]
Tried and tested. The dataloader works well on my side. One minor thing, could you please add `_LANGUAGES = ["psp"]`? Thank you for your hard work, @IvanHalimP!! 💪

**Comment by sabilmakbar** [comment]
> Please find my answers below:
> 
> I don't find cv2 library in the seacrowd's requirements.txt.
> As far as I can remember, I didn't face any issues back then when installing it into the env-seacrowd environment.

In that case, would you like to add another PR for requirements change? ideally config changes should be separated from Dataloader PR

**Review by holylovenia — APPROVED** [review]
Thanks for the change, @IvanHalimP! LGTM. Let's wait for @jamesjaya's review~

**Review by jamesjaya — APPROVED** [review]
tested, lgtm

**Pull request merged**
