### PR TITLE
Remove `CONTRIBUTING.md`, update PR Message Template, and add bash to initialize dataset

### PR DESCRIPTION
**Pull request by sabilmakbar**
Changelogs:
1. Adding a minor bash script utilizes `template/templates.py` to generate a new dataloader folder that conforms to our directory structure and `__init__.py` presence.
2. Delete `CONTRIBUTING.md` since it's duplicated with `DATALOADER.md` on its content. Please advise if we shouldn't delete it, I've made the necessary changes in SEACrowd `README` homepage aswell.
3. Update PR Message Template to clarify wordings and update `_LOCAL` variable as checklisted variables.

Please take a look and see if it can improve our onboarding steps for new contributors.

### CODE REVIEW

**Comment by tellarin** [comment]
@sabilmakbar I was going to propose the same deletion of the duplicate contribution file. 😊

**Review by tellarin — APPROVED** [review]
LGTM

**Review by holylovenia — CHANGES_REQUESTED** [review]
Hi @sabilmakbar, awesome! Thanks a lot for the initiative. 👍 Could I please ask you to change these as well?

1. template.py line 70: `# TODO: Add the licence for the dataset here` --> `# TODO: Add the licence for the dataset here (see constant choices in https://github.com/SEACrowd/seacrowd-datahub/blob/master/seacrowd/utils/constants.py)`
2. template.py line 88: `# TODO: add supported task by dataset. One dataset may support multiple tasks` --> `# TODO: add supported task by dataset. One dataset may support multiple tasks (see constant choices in https://github.com/SEACrowd/seacrowd-datahub/blob/master/seacrowd/utils/constants.py)`

**Comment by sabilmakbar** [comment]
> Thanks a lot for the initiative. 👍 Could I please ask you to change these as well?
> 
> 1. template.py line 70: # TODO: Add the licence for the dataset here --> # TODO: Add the licence for the dataset here (see constant choices in https://github.com/SEACrowd/seacrowd-datahub/blob/master/seacrowd/utils/constants.py)
> 2. template.py line 88: # TODO: add supported task by dataset. One dataset may support multiple tasks --> # TODO: add supported task by dataset. One dataset may support multiple tasks (see constant choices in https://github.com/SEACrowd/seacrowd-datahub/blob/master/seacrowd/utils/constants.py)

done, pls check again, thx!

**Review by holylovenia — APPROVED** [review]
LGTM! Thanks @sabilmakbar.

**Pull request merged**
