### PR TITLE
Closes #70 | Add MABL dataloader

### LINKED ISSUE #70: Create dataset loader for MABL
Dataloader name: `mabl/mabl.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?mabl

|     Dataset| mabl |
|-------------|---|
| Description | The MABL (Metaphors Across Borders and Languages) dataset is a collection of 6,366 figurative language expressions from seven languages, crafted to improve multilingual models' understanding of figurative speech and its linguistic variations. It was built by crowdsourcing native speakers to generate paired metaphors that began with the same words but had different meanings, as well as the literal interpretations of both phrases. Each expression was checked by fluent speakers to ensure they were clear, appropriate, and followed the format, discarding any that didn't meet these standards. |
| Subsets | ind, jav, sun |
| Languages | ind, jav, sun |
| Tasks | Question Answering |
| License | MIT (mit) |
| Homepage | https://github.com/simran-khanuja/Multilingual-Fig-QA |
| HF URL | https://huggingface.co/datasets/dbarbedillo/SMS_Spam_Multilingual_Collection_Dataset |
| Paper URL | https://aclanthology.org/2023.findings-acl.525 |

### PR DESCRIPTION
**Pull request by ljvmiranda921**
Closes #70

Notes
- Although multilingual, `mabl_source` and `mabl_seacrowd` are implemented. In this case, it loads all languages. 
- Might need another set of eyes to check the items in my seacrowd schema. I included the `startphrase` in both the `question` and `context`. Not sure if I should just leave one blank.

```
python -m tests.test_seacrowd seacrowd/sea_datasets/mabl/mabl.py  # Loads all data for all languages
python -m tests.test_seacrowd seacrowd/sea_datasets/mabl/mabl.py --subset_id mabl_jav  # Loads jav subset others: [ind, sun]
```

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

### CODE REVIEW

**Comment by ryanignatius** [comment]
> Might need another set of eyes to check the items in my seacrowd schema. I included the startphrase in both the question and context. Not sure if I should just leave one blank.

IMO, the startphrase is more like a context than a question to me,
I prefer to set it on the context only and leave the question blank

**Comment by ryanignatius** [comment]
on second thought, the question should not be blank,
so maybe it's better to set startphrase in question and leave the context blank

**Comment by ljvmiranda921** [comment]
> on second thought, the question should not be blank,
so maybe it's better to set startphrase in question and leave the context blank

Got it will do this

**Comment by yongzx** [comment]
@ryanignatius anything else before I merge this?

**Review by ryanignatius — APPROVED** [review]
reviewed and tested too,
LGTM

**Comment by ryanignatius** [comment]
> @ryanignatius anything else before I merge this?

no, please proceed to merge 🎉

**Pull request merged**
