### PR TITLE
Closes #584 | Add/Update Dataloader ViLexNorm

### LINKED ISSUE #584: Create dataset loader for ViLexNorm
Dataloader name: `vilexnorm/vilexnorm.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?vilexnorm

|     Dataset| vilexnorm |
|-------------|---|
| Description | The ViLexNorm corpus is a collection of comment pairs in Vietnamese, designed for the task of lexical normalization. The corpus contains 10,467 comment pairs, carefully curated and annotated for lexical normalization purposes. These comment pairs are partitioned into three subsets: training, development, and test, distributed in an 8:1:1 ratio. |
| Subsets | - |
| Languages | vie |
| Tasks | Lexical Normalization |
| License | Creative Commons Attribution Non Commercial Share Alike 4.0 (cc-by-nc-sa-4.0) |
| Homepage | https://github.com/ngxtnhi/ViLexNorm |
| HF URL | - |
| Paper URL | https://aclanthology.org/2024.eacl-long.85/ |

### PR DESCRIPTION
**Pull request by patrickamadeus**
Closes #584 

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/{my_dataset}/{my_dataset}.py` (please use only lowercase and underscore for dataset folder naming, as mentioned in dataset issue) and its `__init__.py` within `{my_dataset}` folder.
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_LOCAL`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py` or `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py --subset_id {subset_name_without_source_or_seacrowd_suffix}`.
- [.] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

### TESTS
image

### CODE REVIEW

**Review by fhudi — APPROVED** [review]
LGTM.
Passed the tests and checklist.
Thanks for the hardwork 🎉

**Review by elyanah-aco — COMMENTED** [review]
Thanks for the PR @patrickamadeus, dataloader works well! Just a minor fix before I approve, please run `make check_file` to fix code formatting.

**Comment by patrickamadeus** [comment]
It's done @elyanah-aco ! Thank you for addressing.

**Review by elyanah-aco — APPROVED** [review]
Thanks @patrickamadeus, merging in a bit!

**Pull request merged**
