### PR TITLE
Closes #210 | Create dataset loader for Orchid Corpus

### LINKED ISSUE #210: Create dataset loader for Orchid Corpus
Dataloader name: `orchid_pos/orchid_pos.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?orchid_pos

|     Dataset| orchid_pos |
|-------------|---|
| Description | The ORCHID corpus is a Thai part-of-speech (POS) tagged dataset, resulting from a collaboration between Japan's Communications Research Laboratory (CRL) and Thailand's National Electronics and Computer Technology Center (NECTEC). It is structured at three levels: paragraph, sentence, and word. The dataset incorporates a unique tagset designed for use in multi-lingual machine translation projects, and is tailored to address the challenges of Thai text, which lacks explicit word and sentence boundaries, punctuation, and inflection. This dataset includes text information along with numbering for retrieval, and employs a probabilistic trigram model for word segmentation and POS tagging. The ORCHID corpus is specifically structured to reduce ambiguity in POS assignments, making it a valuable resource for Thai language processing and computational linguistics research. |
| Subsets | - |
| Languages | tha |
| Tasks | POS Tagging |
| License | Creative Commons Attribution Non Commercial Share Alike 3.0 (cc-by-nc-sa-3.0) |
| Homepage | https://github.com/wannaphong/corpus_mirror/releases/tag/orchid-v1.0 |
| HF URL | - |
| Paper URL | https://www.jstage.jst.go.jp/article/ast1980/20/3/20_3_189/_pdf/-char/en |

### PR DESCRIPTION
**Pull request by MJonibek**
Closes #210 

Please name your PR after the issue it closes. You can use the following line: "Closes #ISSUE-NUMBER" where you replace the ISSUE-NUMBER with the one corresponding to your dataset.

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

### CODE REVIEW

**Review by jamesjaya — APPROVED** [review]
tested and also checked the number of entries with the raw file, lgtm.

question to the maintainers @sabilmakbar @SamuelCahyawijaya @holylovenia, in this implementation, `orchid_pos_source` still loads the raw `File` section which is not very usable out of the box. Since @MJonibek has implemented `_get_tokens_labels` function that parses the `File` section, should we just output the parsed token + label for `orchid_pos_source`?

**Review by holylovenia — CHANGES_REQUESTED** [review]
Hi @MJonibek, I have a question. Is the mismatched result (Train 10) an expected behavior? I feel like the other samples are also a bit different. Are the `tokens` in the `seacrowd` schema derived from `File` in the `source` schema?

### `seacrowd_seq_label` result

```
DatasetDict({
    train: Dataset({
        features: ['id', 'tokens', 'labels'],
        num_rows: 164
    })
})

Train 0
{'id': '0',
 'labels': [41, 10, 4, 4, 46, 34, 26, 4, 4, 36, 4, 4, 46, 1, 31, 46, 26, 0, 0,
            4, 26, 46, 26, 46, 4, 46, 1, 4, 46, 31, 46, 1],
 'tokens': ['การ', 'ประชุม', 'ทาง', 'วิชาการ', '<space>', 'ครั้ง', 'ที่ 1',
            'โครงการวิจัยและพัฒนา', 'อิเล็กทรอนิกส์', 'และ', 'คอมพิวเตอร์',
            'ปีงบประมาณ', '<space>', '2531', 'เล่ม', '<space>', '1',
            'ศูนย์เทคโนโลยีอิเล็กทรอนิกส์และคอมพิวเตอร์แห่งชาติ',
            'กระทรวงวิทยาศาสตร์ เทคโนโลยีและการพลังงาน', 'วัน', 'ที่ 15',
            '<minus>', '16', '<space>', 'สิงหาคม', '<space>', '2532',
            'ห้องประชุม', '<space>', 'ชั้น', '<space>', '4']}

Train 10
{'id': '20', 'labels': [], 'tokens': []}

Train 100
{'id': '100',
 'labels': [5, 0, 46, 0, 4, 0, 46, 0, 5, 0, 46, 0, 5, 0, 46, 0, 4, 4, 4, 4, 4,
            4, 0, 4, 4, 14, 10, 11, 4, 42, 12, 39, 4, 4, 46, 42, 12, 39, 41, 10,
            39, 41, 10, 36, 10, 4, 38, 11, 39, 4, 36, 4, 38, 10, 4, 36, 4, 39,
            41, 10, 19, 46, 12, 37, 4, 9, 10, 27, 17, 39, 4, 4, 10, 41, 10, 36,
            10, 4, 46, 36, 46, 4, 46, 9, 10, 39, 4, 4, 46, 4, 46, 11, 4, 39, 41,
            10, 46, 41, 10, 41, 10, 4, 39, 4, 46, 36, 41, 10, 4, 46, 36, 4, 10,
            41, 10, 39, 4, 46, 17, 42, 12, 39, 4, 39, 4, 9, 14, 10, 17, 17, 46,
            39, 4, 38, 41, 10, 39, 4, 11, 39, 4, 39, 41, 10, 46, 36, 41, 14, 39,
            4, 39, 46, 4, 46, 10, 4, 46, 19, 46, 11, 4, 39, 41, 10, 4, 4, 4, 46,
            36, 39, 4, 36, 4, 4, 9, 10, 39, 4, 19, 11, 4, 9, 10, 39, 4, 38, 4,
            39, 4, 19, 11, 46, 41, 10, 41, 10, 39, 6, 9, 11, 39, 41, 10, 4, 4,
            4, 14, 11, 46, 36, 10, 39, 4, 39, 4, 46, 19, 38, 4, 4, 46, 4, 46, 9,
            11, 10, 27, 17, 42, 12, 39, 4, 45, 15, 10, 17, 41, 10, 13, 11, 4,
            41, 10, 41, 10, 39, 4, 4, 46, 4, 46, 39, 3, 10, 46, 4, 46, 39, 0,
            46, 0, 38, 39, 4, 39, 41, 10, 13, 11, 39, 4, 41, 10, 46, 41, 10, 36,
            10, 4, 39, 4, 46, 25, 46, 31, 46, 36, 46, 25, 46, 31, 46, 41, 10, 4,
            39, 4, 39, 41, 10, 4, 4, 46, 4, 46, 41, 10, 39, 4, 36, 4, 23, 46,
            31, 27, 46, 41, 10, 4, 39, 4, 4, 46, 4, 46, 36, 4, 46, 4, 46, 41,
            10, 4, 39, 4, 39, 4, 39, 4, 22, 46, 39, 4, 46, 25, 46, 31, 46, 41,
            10, 41, 10, 4, 39, 4, 46, 38, 10, 4, 12, 39, 46, 4, 4, 41, 10, 41,
            10, 39, 4, 46, 9, 11, 39, 41, 10, 14, 11, 17, 17, 4, 9, 13, 11, 39,
            4, 19, 46, 13, 10, 4, 14, 10, 39, 41, 12, 39, 4, 46, 39, 41, 10, 4,
            4, 39, 4, 38, 11, 4, 9, 13, 10, 41, 10, 36, 10, 4, 46, 4, 46, 4, 46,
            36, 46, 4, 46, 9, 10, 39, 4, 4, 46, 4, 46, 17, 46, 38, 10, 17, 7,
            39, 0, 46, 38, 45, 15, 10, 4, 39, 4, 38, 41, 10, 36, 10, 4, 46, 4,
            46, 4, 46, 36, 46, 4, 46, 18, 46, 38, 14, 11, 39, 41, 10, 41, 10,
            39, 4, 9, 10, 39, 41, 10, 39, 4, 19],
 'tokens': ['นาย', 'สัจจาทิพย์', '<space>', 'ทัศนียพันธ์', 'นาย', 'ปราโมทย์',
            '<space>', 'ศรีสุขสันต์', 'นาย', 'สมพงษ์', '<space>', 'พิเชฐภิญโญ',
            'นาย', 'ชัยวัฒน์', '<space>', 'ชัยกุล', 'ภาควิชา',
            'วิศวกรรมเครื่องกล', 'ภาควิชา', 'วิศวกรรมไฟฟ้า', 'คณะ',
            'วิศวกรรมศาสตร์', 'มหาวิทยาลัยเกษตรศาสตร์', 'บทคัดย่อ',
            'คอมพิวเตอร์', 'ได้', 'เข้ามา', 'มี', 'บทบาท', 'อย่าง', 'มาก', 'ใน',
            'วงการ', 'อุตสาหกรรม', '<space>', 'โดย', 'เฉพาะ', 'ใน', 'การ',
            'ช่วย', 'ใน', 'การ', 'ออกแบบ', 'และ', 'พัฒนา', 'สินค้า', 'เพื่อให้',
            'ได้มา', 'ซึ่ง', 'คุณภาพ', 'และ', 'มาตรฐาน', 'โดย', 'ใช้',
            'ระยะเวลา', 'และ', 'งบประมาณ', 'ของ', 'การ', 'ลงทุน', 'นั้น',
            '<space>', 'ต่ำ', 'กว่า', 'วิธี', 'ที่', 'ปฏิบัติ', 'กัน', 'อยู่',
            'ใน', 'ปัจจุบัน', 'ซอฟท์แวร์', 'ช่วย', 'การ', 'ออกแบบ', 'และ',
            'ช่วย', 'งานวิศวกรรม', '<space>', 'หรือ', '<space>', 'CAD',
            '<space>', 'ที่', 'ใช้', 'บน', 'เครื่องคอมพิวเตอร์', 'ระดับ',
            '<space>', 'work station', '<space>', 'มี', 'ีประสิทธิภาพ', 'ใน',
            'การ', 'ออกแบบ', '<space>', 'การ', 'จำลอง', 'การ', 'ขึ้น', 'รูปแบบ',
            'ของ', 'เครื่อง CNC Milling', '<space>', 'และ', 'การ', 'ส่ง',
            'รหัส', '<space>', 'หรือ', 'คำสั่ง', 'ควบคุม', 'การ', 'ทำงาน',
            'ของ', 'เครื่อง CNC', '<space>', 'ได้', 'โดย', 'อัตโนมัติ', 'จาก',
            'ขนาด', 'ของ', 'ชิ้นงาน', 'ที่', 'ได้', 'ออกแบบ', 'ขึ้น', 'แล้ว',
            '<space>', 'บน', 'คอมพิวเตอร์', 'ซึ่ง', 'การ', 'ทำงาน', 'ของ',
            'ซอฟต์แวร์', 'ประกอบ', 'กับ', 'ประสิทธิภาพ', 'ใน', 'การ', 'คำนวณ',
            '<space>', 'และ', 'ความ', 'สามารถ', 'ของ', 'กราฟฟิก', 'ของ',
            '<space>', 'work station', '<space>', 'ทำให้', 'ระบบ CAD',
            '<space>', 'นี้', '<space>', 'มี', 'ผลกระทบ', 'ใน', 'การ', 'ผลิต',
            'ชิ้นส่วน', 'ทาง', 'อุตสาหกรรม', '<space>', 'ทั้ง', 'ใน',
            'ปัจจุบัน', 'และ', 'อนาคต', 'ซอฟท์แวร์', 'ที่', 'เสนอ', 'ใน',
            'งานวิจัย', 'นี้', 'เป็น', 'ซอฟท์แวร์', 'ที่', 'มา', 'จาก',
            'ต่างประเทศ', 'ซึ่ง', 'ส่วนหนึ่ง', 'ของ', 'โครงการวิจัย', 'นี้',
            'คือ', '<space>', 'การ', 'ให้', 'การ', 'ฝึกอบรม', 'แก่', 'ผู้',
            'ที่', 'เกี่ยวข้อง', 'กับ', 'การ', 'ผลิต', 'สินค้า', 'ทาง',
            'อุตสาหกรรม', 'ได้', 'รู้จัก', '<space>', 'และ', 'ทราบ', 'ถึง',
            'ประสิทธิภาพ', 'ของ', 'ระบบ CAD', '<space>', 'นี้', 'ซึ่ง',
            'เครื่องคอมพิวเตอร์', 'ระดับ', '<space>', 'IBM compatible',
            '<space>', 'ที่', 'มี', 'ใช้', 'กัน', 'อยู่', 'อย่าง', 'แพร่หลาย',
            'ใน', 'ปัจจุบัน', 'มิ', 'อาจ', 'เปรียบเทียบ', 'ได้', 'การ', 'อบรม',
            'จะ', 'เป็น', 'แบบ', 'การ', 'ฝึกปฏิบัติ', 'การ', 'ใช้งาน', 'บน',
            'เครื่องคอมพิวเตอร์', 'ระดับ', '<space>', 'work station', '<space>',
            'ที่', 'ศูนย์', 'ปฏิบัติการ', '<space>', 'CAD', '<space>', 'ของ',
            'ศูนย์เทคโนโลยีอิเล็กทรอนิกส์และคอมพิวเตอร์แห่งชาติ', '<space>',
            'กระทรวงวิทยาศาสตร์ฯ', 'ซึ่ง', 'ใน', 'หลักสูตร', 'ของ', 'การ',
            'ฝึกอบรม', 'จะ', 'ประกอบ', 'ด้วย', 'พื้นฐาน', 'การ', 'ออกแบบ',
            '<space>', 'การ', 'เขียนแบบ', 'และ', 'แก้ไข', 'แบบ', 'ใน', 'ภาพวิว',
            '<space>', '2', '<space>', 'มิติ', '<space>', 'และ', '<space>', '3',
            '<space>', 'มิติ', '<space>', 'การ', 'ตรวจสอบ', 'รายละเอียด', 'ของ',
            'ชิ้นงาน', 'จาก', 'การ', 'ฉาย', 'ภาพ', 'แบบ', '<space>',
            'orthographic', '<space>', 'การ', 'ประกอบ', 'ของ', 'ชิ้นงาน',
            'หรือ', 'ชิ้นส่วน', 'หลายๆ', '<space>', 'ชิ้น', 'เข้าด้วยกัน',
            '<space>', 'การ', 'แสดง', 'พื้นผิว', 'ของ', 'ชิ้นงาน', 'แบบ',
            '<space>', 'wire frame', '<space>', 'และ', 'แบบ', '<space>',
            'solid modeling', '<space>', 'การ', 'ตรวจสอบ', 'รายละเอียด', 'ของ',
            'พื้นผิว', 'ของ', 'ชิ้นงาน', 'ที่', 'มุมมอง', 'ต่างๆ', '<space>',
            'จาก', 'ภาพ', '<space>', '3', '<space>', 'มิติ', '<space>', 'การ',
            'จำลอง', 'การ', 'ขึ้น', 'รูปแบบ', 'ของ', 'เครื่อง CNC', '<space>',
            'เพื่อ', 'ตรวจสอบ', 'ทาง', 'เดิม', 'ของ', '<space>', 'cutting tool',
            'คำสั่ง', 'การ', 'ควบคุม', 'การ', 'ทำงาน', 'ของ', 'เครื่อง CNC',
            '<space>', 'ที่', 'เกิดขึ้น', 'หลังจาก', 'การ', 'จำลอง', 'ได้',
            'เสร็จสิ้น', 'ลง', 'แล้ว', 'ผล', 'ที่', 'จะ', 'ได้รับ', 'จาก',
            'โครงการ', 'นี้', '<space>', 'จะ', 'ทำให้', 'ภาคอุตสาหกรรม', 'ได้',
            'เล็งเห็น', 'ถึง', 'ความ', 'สำคัญ', 'ของ', 'ระบบ CAD', '<space>',
            'ต่อ', 'การ', 'พัฒนา', 'สินค้า', 'อุตสาหกรรม', 'ของ', 'ตน', 'อัน',
            'เป็น', 'แรงกระตุ้น', 'ที่', 'จะ', 'ก่อให้เกิด', 'การ', 'วิจัย',
            'และ', 'พัฒนา', 'ซอฟท์แวร์', '<space>', 'CAD', '<space>', 'CAM',
            '<space>', 'และ', '<space>', 'CAE', '<space>', 'ที่', 'ใช้', 'กับ',
            'เครื่องคอมพิวเตอร์', 'ระดับ', '<space>', 'Work station', '<space>',
            'ขึ้น', '<space>', 'เพื่อ', 'ใช้', 'ได้', 'เอง', 'ใน', 'ประเทศไทย',
            '<space>', 'โดย', 'มิ', 'ต้อง', 'พึ่ง', 'เทคโนโลยี', 'จาก',
            'ต่างประเทศ', 'ซึ่ง', 'การ', 'วิจัย', 'และ', 'พัฒนา', 'ซอฟท์แวร์',
            '<space>', 'CAD', '<space>', 'CAM', '<space>', 'และ', '<space>',
            'CAE', '<space>', 'ดังกล่าว', '<space>', 'ก็', 'สามารถ', 'เริ่มต้น',
            'จาก', 'การ', 'ศึกษา', 'การ', 'ทำงาน', 'ของ', 'ซอฟท์แวร์', 'ที่',
            'ใช้', 'ใน', 'การ', 'ฝึกอบรม', 'ของ', 'โครงการวิจัย', 'นี้']}
```

### `source` result

```
DatasetDict({
    train: Dataset({
        features: ['TTitle', 'ETitle', 'TAuthor', 'EAuthor', 'TInbook', 'EInbook', 'TPublisher', 'EPublisher', 'Page', 'Year', 'File'],
        num_rows: 164
    })
})

Train 0
{'EAuthor': '\n',
 'EInbook': ' The 1st Annual Conference, Electronics and Computer Research and '
            'Development Project, Fiscal Year 1988, Book 1\n',
 'EPublisher': ' National Electronics and Computer Technology Center, Ministry '
               'of Science, Technology and Energy\n',
 'ETitle': ' [1st Annual Conference]\n',
 'File': '\n'
         '#P1\n'
         '#1\n'
         'การประชุมทางวิชาการ ครั้งที่ 1//\n'
         'การ/FIXN\n'
         'ประชุม/VACT\n'
         'ทาง/NCMN\n'
         'วิชาการ/NCMN\n'
         '<space>/PUNC\n'
         'ครั้ง/CFQC\n'
         'ที่ 1/DONM\n'
         '//\n'
         '#2\n'
         'โครงการวิจัยและพัฒนาอิเล็กทรอนิกส์และคอมพิวเตอร์//\n'
         'โครงการวิจัยและพัฒนา/NCMN\n'
         'อิเล็กทรอนิกส์/NCMN\n'
         'และ/JCRG\n'
         'คอมพิวเตอร์/NCMN\n'
         '//\n'
         '#3\n'
         'ปีงบประมาณ 2531//\n'
         'ปีงบประมาณ/NCMN\n'
         '<space>/PUNC\n'
         '2531/NCNM\n'
         '//\n'
         '#4\n'
         'เล่ม 1//\n'
         'เล่ม/CNIT\n'
         '<space>/PUNC\n'
         '1/DONM\n'
         '//\n'
         '#P2\n'
         '#1\n'
         'ศูนย์เทคโนโลยีอิเล็กทรอนิกส์และคอมพิวเตอร์แห่งชาติ//\n'
         'ศูนย์เทคโนโลยีอิเล็กทรอนิกส์และคอมพิวเตอร์แห่งชาติ/NPRP\n'
         '//\n'
         '#2\n'
         'กระทรวงวิทยาศาสตร์ เทคโนโลยีและการพลังงาน//\n'
         'กระทรวงวิทยาศาสตร์ เทคโนโลยีและการพลังงาน/NPRP\n'
         '//\n'
         '#P3\n'
         '#1\n'
         'วันที่ 15-16 สิงหาคม 2532//\n'
         'วัน/NCMN\n'
         'ที่ 15/DONM\n'
         '<minus>/PUNC\n'
         '16/DONM\n'
         '<space>/PUNC\n'
         'สิงหาคม/NCMN\n'
         '<space>/PUNC\n'
         '2532/NCNM\n'
         '//\n'
         '#2\n'
         'ห้องประชุม ชั้น 4//\n'
         'ห้องประชุม/NCMN\n'
         '<space>/PUNC\n'
         'ชั้น/CNIT\n'
         '<space>/PUNC\n'
         '4/NCNM\n'
         '//\n',
 'Page': '\n',
 'TAuthor': '\n',
 'TInbook': ' การประชุมทางวิชาการ ครั้งที่ 1, '
            'โครงการวิจัยและพัฒนาอิเล็กทรอนิกส์และคอมพิวเตอร์, ปีงบประมาณ '
            '2531, เล่ม 1\n',
 'TPublisher': ' ศูนย์เทคโนโลยีอิเล็กทรอนิกส์และคอมพิวเตอร์แห่งชาติ, '
               'กระทรวงวิทยาศาสตร์ เทคโนโลยีและการพลังงาน\n',
 'TTitle': ' การประชุมทางวิชาการ ครั้งที่ 1\n',
 'Year': ' 1989\n'}

Train 10
{'EAuthor': '\n',
 'EInbook': ' The 1st Annual Conference, Electronics and Computer Research and '
            'Development Project, Fiscal Year 1988, Book 1\n',
 'EPublisher': ' National Electronics and Computer Technology Center, Ministry '
               'of Science, Technology and Energy\n',
 'ETitle': ' Design and Fabrication of Prototype IC\n',
 'File': '\n'
         '#P1\n'
         '#1\n'
         'การออกแบบและการสร้างวงจรรวมต้นแบบ//\n'
         'การ/FIXN\n'
         'ออกแบบ/VACT\n'
         'และ/JCRG\n'
         'การ/FIXN\n'
         'สร้าง/VACT\n'
         'วงจรรวม/NCMN\n'
         'ต้นแบบ/NCMN\n'
         '//\n'
         '#P2\n'
         '#1\n',
 'Page': '\n',
 'TAuthor': ' สมเกียรติ ศุภเดช, สมศักดิ์ ชุ่มช่วย และ วิสุทธิ์ ฐิติรุ่งเรือง\n',
 'TInbook': ' การประชุมทางวิชาการ ครั้งที่ 1, '
            'โครงการวิจัยและพัฒนาอิเล็กทรอนิกส์และคอมพิวเตอร์, ปีงบประมาณ '
            '2531, เล่ม 1\n',
 'TPublisher': ' ศูนย์เทคโนโลยีอิเล็กทรอนิกส์และคอมพิวเตอร์แห่งชาติ, '
               'กระทรวงวิทยาศาสตร์ เทคโนโลยีและการพลังงาน\n',
 'TTitle': ' การออกแบบและการสร้างวงจรรวมต้นแบบ\n',
 'Year': ' 1989\n'}

Train 100
{'EAuthor': '\n',
 'EInbook': ' The 3rd Annual Conference, Electronics and Computer Research and '
            'Development Project, Fiscal Year 1990, Book 2\n',
 'EPublisher': ' National Electronics and Computer Technology Center, Ministry '
               'of Science, Technology and Energy\n',
 'ETitle': ' The Use of CAD2CAE Software for Designing and Developing of '
           'Industrial Products\n',
 'File': '\n'
         '#P1\n'
         '#1\n'
         'ชื่อโครงการ//\n'
         'ชื่อ/NCMN\n'
         'โครงการ/NCMN\n'
         '//\n'
         '#P2\n'
         '#1\n'
         'โครงการพัฒนาซอฟท์แวร์เพื่ออุตสาหกรรม//\n'
         'โครงการ/NCMN\n'
         'พัฒนา/VACT\n'
         'ซอฟท์แวร์/NCMN\n'
         'เพื่อ/RPRE\n'
         'อุตสาหกรรม/NCMN\n'
         '//\n'
         '#P3\n'
         '#1\n',
 'Page': '\n',
 'TAuthor': ' สัจจาทิพย์ ทัศนียพันธ์, ปราโมทย์ ศรีสุขสันต์, สมพงษ์ พิเชฐภิญโญ, '
            'ชัยวัฒน์ ชัยกุล\n',
 'TInbook': ' การประชุมทางวิชาการ ครั้งที่ 3, '
            'โครงการวิจัยและพัฒนาอิเล็กทรอนิกส์และคอมพิวเตอร์, ปีงบประมาณ '
            '2533, เล่ม 2\n',
 'TPublisher': ' ศูนย์เทคโนโลยีอิเล็กทรอนิกส์และคอมพิวเตอร์แห่งชาติ, '
               'กระทรวงวิทยาศาสตร์ เทคโนโลยีและการพลังงาน\n',
 'TTitle': ' การใช้ซอฟท์แวร์ CAD2CAE '
           'เพื่อออกแบบและพัฒนาต้นแบบของสินค้าทางอุตสาหกรรม\n',
 'Year': ' 1991\n'}
```

**Comment by MJonibek** [comment]
@holylovenia Fixed it. The problem was that the file was not consistent with its annotations. Sometimes there were some english sentences that started with %E, and it was breaking whole parser from the beginning. Also, sometimes instead of using `/` to divide between the token and its label, they used `@` (have no idea why). I fixed these problems. I checked some cases, seem good to me (but it is really hard to check them because of the language).

**Review by holylovenia — CHANGES_REQUESTED** [review]
Thanks for fixing the bug, @MJonibek. Other than a few leftover nits, I think the dataloader works well.

1. Could you please `.strip()` all the field values in the `source` schema? It seems they have many leading and/or trailing whitespaces.

2. Should we replace `<space>`, `<comma>`, `<left_parenthesis>`, etc. with ` `, `,`, `(`, etc. for the `tokens` in both schemas? If you think retaining the current `<...>` format is better, feel free to give your feedback, @MJonibek @jamesjaya.

**Comment by MJonibek** [comment]
@holylovenia made changes for both points. I agree that it would be better to replace this special char

**Review by holylovenia — APPROVED** [review]
LGTM!! 👍 Thank you @MJonibek. Very reliable as always.

**Pull request merged**
