### PR TITLE
Closes #83 | Implement Dataloader for GlobalWoZ

### LINKED ISSUE #83: Create dataset loader for GlobalWoZ V2.0
Dataloader name: `globalwoz_v2.0/globalwoz_v2.0.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?globalwoz_v2.0

|     Dataset| globalwoz_v2.0 |
|-------------|---|
| Description | This is the data of the paper “GlobalWoZ: Globalizing MultiWoZ to Develop Multilingual Task-Oriented Dialogue Systems” accepted by ACL 2022. The dataset contains several sub-datasets in 20 languages and 3 schemes (F&E, E&F, F&F), including Indonesian (id), Thai (th), and Vietnamese (vi) language. The method is based on translating dialogue templates and filling them with local entities in
the target language countries. |
| Subsets | E&F_id, E&F_th, E&F_vi, F&E_id, F&E_th, F&E_vi, F&F_id, F&F_th, F&F_vi |
| Languages | ind, tha, vie |
| License | Unknown (unknown) |
| Homepage | https://entuedu-my.sharepoint.com/:f:/g/personal/bosheng001_e_ntu_edu_sg/EhlGX7Bmi8pMsdZsm6gQr4oBgI4Z7kFznovkuDOdixfLUg?e=kbo7kz |
| HF URL | - |
| Paper URL | https://aclanthology.org/2022.acl-long.115.pdf |

### PR DESCRIPTION
**Pull request by dehanalkautsar**
Closes #83.

### Note
- For the TOD SEACrowd Schema features, I left the turn_label feature key in this dataloader as an empty array because this dataset does not have them.
- `system_acts` will be populated with the `dialog_act` from the user utterance in the original dataset, as our schema dictates that `system_acts` should represent the system's intended actions based on the user's utterance.
- Additionally, the `belief_state` will be populated with the `span_info` from the user utterance in the original dataset, as our schema dictates that `belief_state` should represent the system's belief state based on the user's utterance, not the system_utterance.
- Some key features from the source dataset have not been incorporated into the SEACrowd TOD schema, as no corresponding features align with those in the schema (e.g., `goal` and `log.metadata`).

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

### Output of The Unit-test
Because this is a local dataset (I have some problems while loading the datasets directly from OneDrive URLs, so I need to download them via this link https://entuedu-my.sharepoint.com/personal/bosheng001_e_ntu_edu_sg/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fbosheng001%5Fe%5Fntu%5Fedu%5Fsg%2FDocuments%2Fglobalwoz%5Fv2&ga=1),

My Unit-test script
```
python -m tests.test_seacrowd seacrowd/sea_datasets/globalwoz/globalwoz.py --data_dir=./dataset/globalwoz --subset_id globalwoz_EandF_id
``` 

Unit-test output
```
INFO:__main__:args: Namespace(path='seacrowd/sea_datasets/globalwoz/globalwoz.py', schema=None, subset_id='globalwoz_EandF_id', data_dir='./dataset/globalwoz', use_auth_token=None)
INFO:__main__:self.PATH: seacrowd/sea_datasets/globalwoz/globalwoz.py
INFO:__main__:self.SUBSET_ID: globalwoz_EandF_id
INFO:__main__:self.SCHEMA: None
INFO:__main__:self.DATA_DIR: ./dataset/globalwoz
INFO:__main__:Checking for _SUPPORTED_TASKS ...
module seacrowd.sea_datasets.globalwoz.globalwoz
INFO:__main__:Found _SUPPORTED_TASKS=[<Tasks.E2E_TASK_ORIENTED_DIALOGUE: 'TOD'>]
INFO:__main__:_SUPPORTED_TASKS implies _MAPPED_SCHEMAS={'TOD'}
INFO:__main__:schemas_to_check: {'TOD'}
INFO:__main__:Checking load_dataset with config name globalwoz_EandF_id_source
D:\External\seacrowd-datahub\venv\lib\site-packages\datasets\load.py:2088: FutureWarning: 'use_auth_token' was deprecated in favor of 'token' in version 2.14.0 and will be removed in 3.0.0.
You can remove this warning by passing 'token=<use_auth_token>' instead.
  warnings.warn(
INFO:__main__:Checking load_dataset with config name globalwoz_EandF_id_seacrowd_tod
D:\External\seacrowd-datahub\venv\lib\site-packages\datasets\load.py:2088: FutureWarning: 'use_auth_token' was deprecated in favor of 'token' in version 2.14.0 and will be removed in 3.0.0.
You can remove this warning by passing 'token=<use_auth_token>' instead.
  warnings.warn(
INFO:__main__:Dataset sample [source]
{'id': '0', 'goal': {'attraction': '{}', 'hospital': '{}', 'hotel': '{"book": {"day": "Minggu", "invalid": false, "people": "dua", "pre_invalid": true, "stay": "tujuh"}, "fail_book": {"stay": "empat"}, "fail_info": {}, "info": {"internet": "no", "stars": "2", "type": "guesthouse"}}', 'police': '{}', 'restaurant': '{"book": {"day": "Minggu", "invalid": false, "people": "dua", "time": "17:15"}, "fail_book": {}, "fail_info": {}, "info": {"area": "pusat", "food": "Asia", "pricerange": 
"harga sedang"}}', 'taxi': '{}', 'train': '{}'}, 'log': [{'dialog_act': '{"Restaurant-Inform": [["food", "Asia"]]}', 'metadata': '{}', 'span_info': [['restaurant-inform', 'food', 'Asia', '71', '89']], 'text': "i'd really like to take my client out to a nice restaurant that serves Asia food."}, {'dialog_act': '{"Restaurant-Inform": [["choice", "many"], ["food", "Asia"], ["pricerange", "murah"]], "Restaurant-Request": [["area", "?"]]}', 'metadata': '{"attraction": {"book": {"booked": []}, "semi": {"area": [], "name": [], "type": []}}, "hospital": {"book": {"booked": []}, "semi": {"department": []}}, "hotel": {"book": {"booked": [], "day": [], "people": [], "stay": []}, "semi": {"area": [], "internet": [], "name": [], "parking": [], "pricerange": [], "stars": [], "type": []}}, "police": {"book": {"booked": []}, "semi": {}}, "restaurant": {"book": {"booked": [], "day": [], "people": [], "time": []}, "semi": {"area": [], "food": ["Asia"], "name": [], "pricerange": ["harga sedang"]}}, "taxi": {"book": {"booked": []}, "semi": {"arriveBy": [], "departure": [], "destination": [], "leaveAt": []}}, "train": {"book": {"booked": 
[], "ticket": []}, "semi": {"arriveBy": [], "day": [], "departure": [], "destination": [], "leaveAt": []}}}', 'span_info': [['restaurant-inform', 'choice', 'many', '7', '11'], ['restaurant-inform', 'food', 'Asia', '35', '53'], ['restaurant-inform', 'pricerange', 'murah', '62', '86']], 'text': 'i show many restaurants that 
serve Asia food in murah. what area would you like to travel to?'}, {'dialog_act': '{"Restaurant-Inform": [["area", "pusat"], ["food", "Asia"], ["pricerange", "harga sedang"]]}', 'metadata': '{}', 'span_info': [['restaurant-inform', 'pricerange', 'harga sedang', '20', '44'], ['restaurant-inform', 'food', 'Asia', '45', '63'], ['restaurant-inform', 'area', 'pusat', '90', '108']], 'text': 'i am looking for an harga sedang Asia restaurant in the area of pusat.'}, {'dialog_act': '{"Booking-Inform": [["none", "none"]], "Restaurant-Recommend": [["area", "pusat"], ["food", "Asia"], ["name", "Resto Ngalam"], ["pricerange", "harga sedang"]]}', 'metadata': '{"attraction": {"book": {"booked": []}, "semi": {"area": [], "name": [], "type": []}}, "hospital": {"book": {"booked": []}, "semi": {"department": []}}, "hotel": {"book": {"booked": [], "day": [], "people": [], "stay": []}, "semi": {"area": [], "internet": [], "name": [], "parking": [], "pricerange": [], "stars": [], "type": []}}, "police": {"book": {"booked": []}, "semi": {}}, "restaurant": {"book": {"booked": [], "day": [], "people": [], "time": []}, "semi": {"area": ["pusat"], "food": ["Asia"], "name": [], "pricerange": ["harga sedang"]}}, "taxi": {"book": {"booked": []}, "semi": {"arriveBy": [], "departure": [], "destination": [], "leaveAt": []}}, "train": {"book": {"booked": [], "ticket": []}, "semi": {"arriveBy": [], "day": [], "departure": [], "destination": [], "leaveAt": []}}}', 'span_info': [['restaurant-recommend', 'name', 'Resto Ngalam', '18', '36'], ['restaurant-recommend', 'pricerange', 'harga sedang', '49', '73'], ['restaurant-recommend', 'food', 'Asia', '74', '92'], ['restaurant-recommend', 'area', 'pusat', '111', '129']], 'text': 'might i recommend Resto Ngalam? that is an harga sedang Asia restaurant in the pusat. i can book a table for you, if you like.'}, {'dialog_act': '{"Restaurant-Inform": [["bookday", "Minggu"], ["bookpeople", "dua"], ["booktime", "17:15"]]}', 'metadata': '{}', 'span_info': [['restaurant-inform', 'bookpeople', 'dua', '28', '52'], ['restaurant-inform', 'booktime', '17:15', '63', '85'], ['restaurant-inform', 'bookday', 'Minggu', '89', '110']], 'text': 'sure thing, please book for dua people at 17:15 on Minggu.'}, {'dialog_act': '{"Booking-Book": [["ref", "rf00jufq"]]}', 'metadata': '{"attraction": {"book": {"booked": []}, "semi": {"area": [], "name": [], "type": []}}, "hospital": {"book": {"booked": []}, "semi": {"department": []}}, "hotel": {"book": {"booked": [], "day": [], "people": [], "stay": []}, "semi": {"area": [], "internet": [], "name": [], "parking": [], 
"pricerange": [], "stars": [], "type": []}}, "police": {"book": {"booked": []}, "semi": {}}, "restaurant": {"book": {"booked": [{"name": ["Resto Ngalam"], "reference": "rf00jufq"}], "day": ["Minggu"], "people": ["dua"], "time": ["17:15"]}, "semi": {"area": ["pusat"], "food": ["Asia"], "name": ["Resto Ngalam"], "pricerange": ["harga sedang"]}}, "taxi": {"book": {"booked": []}, "semi": {"arriveBy": [], "departure": [], "destination": [], "leaveAt": []}}, "train": {"book": {"booked": 
[], "ticket": []}, "semi": {"arriveBy": [], "day": [], "departure": [], "destination": [], "leaveAt": []}}}', 'span_info': [['booking-book', 'ref', 'rf00jufq', '94', '102']], 'text': 'booking was successful. the table will be reserved for 15 minutes. your reference number is : rf00jufq .'}, {'dialog_act': '{"Hotel-Inform": [["internet", "no"], ["stars", "2"]]}', 'metadata': '{}', 'span_info': [['hotel-inform', 'stars', '2', '61', '75']], 'text': "okay great! thank you so much. could you also help me find a 2 star hotel in the area. i don't need wifi either."}, {'dialog_act': '{"Booking-Inform": [["none", "none"]], "Hotel-Inform": [["area", 
"selatan"], ["internet", "yes"], ["name", "Everyday Smart Hotel Mayestik"], ["parking", "yes"], ["pricerange", "mahal"], ["stars", "2"]]}', 'metadata': '{"attraction": {"book": {"booked": []}, "semi": {"area": [], "name": [], "type": []}}, "hospital": {"book": {"booked": []}, "semi": {"department": []}}, "hotel": {"book": 
{"booked": [], "day": [], "people": [], "stay": []}, "semi": {"area": [], "internet": ["no"], "name": [], "parking": [], "pricerange": [], "stars": ["2"], "type": []}}, "police": {"book": {"booked": []}, "semi": {}}, "restaurant": {"book": {"booked": [{"name": ["Resto Ngalam"], "reference": "rf00jufq"}], "day": ["Minggu"], "people": ["dua"], "time": ["17:15"]}, "semi": {"area": ["pusat"], "food": ["Asia"], "name": ["Resto Ngalam"], "pricerange": ["harga sedang"]}}, "taxi": {"book": {"booked": []}, "semi": {"arriveBy": [], "departure": [], "destination": [], "leaveAt": []}}, "train": {"book": {"booked": [], "ticket": []}, "semi": {"arriveBy": [], "day": [], "departure": [], "destination": [], "leaveAt": []}}}', 'span_info': [['hotel-inform', 'name', 'Everyday Smart Hotel Mayestik', '0', '14'], ['hotel-inform', 'area', 'selatan', '25', '39'], ['hotel-inform', 'pricerange', 'mahal', '47', '67'], ['hotel-inform', 'stars', '2', '76', '90']], 'text': 'Everyday Smart Hotel Mayestik is in the selatan and is mahal. it has 2 stars and no internet or parking. would you like to book a room?'}, {'dialog_act': '{"Hotel-Inform": [["internet", "no"], ["parking", "no"]]}', 'metadata': '{}', 'span_info': [], 'text': 'that sounds great. please book that now.'}, {'dialog_act': '{"Booking-Request": [["bookpeople", "?"]]}', 'metadata': '{"attraction": {"book": {"booked": []}, "semi": {"area": [], "name": [], "type": []}}, "hospital": {"book": {"booked": []}, "semi": {"department": []}}, "hotel": {"book": {"booked": [], "day": [], "people": [], "stay": []}, "semi": {"area": [], "internet": ["no"], "name": ["Everyday Smart Hotel Mayestik"], "parking": [], "pricerange": [], "stars": ["2"], "type": []}}, "police": {"book": {"booked": []}, "semi": {}}, "restaurant": {"book": {"booked": [{"name": ["Resto Ngalam"], "reference": "rf00jufq"}], "day": ["Minggu"], "people": ["dua"], "time": ["17:15"]}, "semi": {"area": ["pusat"], "food": ["Asia"], "name": ["Resto Ngalam"], "pricerange": ["harga sedang"]}}, "taxi": {"book": {"booked": []}, "semi": {"arriveBy": [], "departure": [], "destination": [], "leaveAt": []}}, "train": {"book": {"booked": [], "ticket": []}, "semi": {"arriveBy": [], "day": [], "departure": [], "destination": [], "leaveAt": []}}}', 'span_info': [], 'text': 'may i ask how many people are in your group?'}, {'dialog_act': '{"Hotel-Inform": [["bookpeople", "dua"]]}', 'metadata': '{}', 'span_info': [['hotel-inform', 'bookpeople', 'dua', '7', '31']], 'text': 'i have dua people in my group.'}, {'dialog_act': '{"Booking-Request": [["bookstay", "?"]]}', 'metadata': '{"attraction": {"book": {"booked": []}, "semi": {"area": [], "name": [], "type": []}}, "hospital": {"book": {"booked": []}, "semi": {"department": []}}, "hotel": {"book": {"booked": [], "day": [], "people": ["dua"], "stay": []}, "semi": {"area": [], "internet": ["no"], "name": ["Everyday Smart Hotel Mayestik"], "parking": [], "pricerange": [], "stars": ["2"], "type": []}}, "police": {"book": {"booked": []}, "semi": {}}, "restaurant": {"book": {"booked": [{"name": ["Resto Ngalam"], "reference": "rf00jufq"}], "day": ["Minggu"], "people": ["dua"], "time": ["17:15"]}, "semi": {"area": ["pusat"], "food": ["Asia"], "name": ["Resto Ngalam"], "pricerange": ["harga sedang"]}}, "taxi": {"book": {"booked": []}, "semi": {"arriveBy": [], "departure": [], "destination": [], "leaveAt": []}}, "train": {"book": {"booked": [], "ticket": []}, "semi": {"arriveBy": [], "day": [], "departure": [], "destination": [], "leaveAt": []}}}', 'span_info': [], 'text': 'how many days would 
you like to stay?'}, {'dialog_act': '{"Hotel-Inform": [["bookday", "Minggu"], ["bookstay", "empat"]]}', 'metadata': '{}', 'span_info': [['hotel-inform', 'bookstay', 'empat', '0', '18'], ['hotel-inform', 'bookday', 'Minggu', '40', '61']], 'text': 'empat nights, starting the Minggu as the reservation.'}, {'dialog_act': '{"Booking-NoBook": [["none", "none"]]}', 'metadata': '{"attraction": {"book": {"booked": []}, "semi": {"area": [], "name": [], "type": []}}, "hospital": {"book": {"booked": []}, "semi": {"department": []}}, "hotel": {"book": {"booked": [], "day": ["Minggu"], "people": ["dua"], "stay": ["empat"]}, "semi": {"area": [], "internet": ["no"], "name": ["Everyday Smart Hotel Mayestik"], "parking": [], "pricerange": [], "stars": ["2"], "type": []}}, "police": {"book": {"booked": []}, "semi": {}}, "restaurant": {"book": {"booked": [{"name": ["Resto Ngalam"], "reference": "rf00jufq"}], "day": ["Minggu"], "people": ["dua"], "time": ["17:15"]}, "semi": {"area": ["pusat"], "food": ["Asia"], "name": ["Resto Ngalam"], "pricerange": ["harga sedang"]}}, "taxi": {"book": {"booked": []}, "semi": {"arriveBy": [], "departure": [], "destination": [], "leaveAt": []}}, "train": {"book": {"booked": [], "ticket": []}, "semi": {"arriveBy": [], "day": [], "departure": [], "destination": [], "leaveAt": []}}}', 'span_info': [], 'text': "i'm sorry. it looks like they're full. would you like me to look for something else?"}, {'dialog_act': '{}', 'metadata': '{}', 'span_info': [], 'text': 'yes please. is there something else available in that area?'}, {'dialog_act': '{"Hotel-Inform": [["area", "barat"], ["stars", "2"], ["type", "homestay"]], "Hotel-Request": [["area", "?"]]}', 'metadata': '{"attraction": {"book": {"booked": []}, "semi": {"area": [], "name": [], "type": []}}, "hospital": {"book": {"booked": []}, "semi": {"department": []}}, "hotel": {"book": {"booked": [], "day": ["Minggu"], "people": ["dua"], "stay": ["empat"]}, "semi": {"area": [], "internet": ["no"], "name": ["Everyday Smart Hotel Mayestik"], "parking": [], "pricerange": [], "stars": ["2"], "type": []}}, "police": {"book": {"booked": []}, "semi": {}}, "restaurant": {"book": {"booked": [{"name": ["Resto Ngalam"], "reference": "rf00jufq"}], "day": ["Minggu"], "people": ["dua"], "time": ["17:15"]}, "semi": {"area": ["pusat"], "food": ["Asia"], "name": ["Resto Ngalam"], "pricerange": ["harga sedang"]}}, "taxi": {"book": {"booked": []}, "semi": {"arriveBy": [], "departure": [], "destination": [], "leaveAt": []}}, "train": {"book": {"booked": [], "ticket": []}, "semi": {"arriveBy": [], "day": [], "departure": [], "destination": [], "leaveAt": []}}}', 'span_info': [['hotel-inform', 'stars', '2', '42', '56'], ['hotel-inform', 'type', 'homestay', '62', '76'], ['hotel-inform', 'area', 'barat', '80', '94']], 'text': "i'm sorry, it looks like that is the only 2 star homestay in barat, would you like me to look somewhere else?"}, {'dialog_act': '{"Hotel-Inform": [["bookstay", "tujuh"]]}', 'metadata': '{}', 'span_info': [['hotel-inform', 'bookstay', 'tujuh', '15', '33']], 'text': "can we try for tujuh night instead of 2? i'll need the reference number please."}, {'dialog_act': '{"Booking-Book": [["bookstay", "lima"], ["ref", "9xvt8m5t"]]}', 'metadata': '{"attraction": {"book": {"booked": []}, "semi": {"area": [], "name": [], "type": []}}, "hospital": {"book": {"booked": []}, "semi": {"department": []}}, "hotel": {"book": {"booked": [{"name": ["Everyday Smart Hotel Mayestik"], "reference": "9xvt8m5t"}], "day": ["Minggu"], "people": ["dua"], "stay": ["tujuh"]}, "semi": {"area": [], "internet": ["no"], "name": ["Everyday Smart Hotel Mayestik"], "parking": [], "pricerange": [], "stars": ["2"], "type": []}}, "police": {"book": 
{"booked": []}, "semi": {}}, "restaurant": {"book": {"booked": [{"name": ["Resto Ngalam"], "reference": "rf00jufq"}], "day": ["Minggu"], "people": ["dua"], "time": ["17:15"]}, "semi": {"area": ["pusat"], "food": ["Asia"], "name": ["Resto Ngalam"], "pricerange": ["harga sedang"]}}, "taxi": {"book": {"booked": []}, "semi": {"arriveBy": [], "departure": [], "destination": [], "leaveAt": []}}, "train": {"book": {"booked": [], "ticket": []}, "semi": {"arriveBy": [], "day": [], "departure": [], "destination": [], "leaveAt": []}}}', 'span_info': [['booking-book', 'bookstay', 'lima', '18', '36'], ['booking-book', 'ref', '9xvt8m5t', '68', '76']], 'text': 'i was able to get lima night, the reference number is 9xvt8m5t .'}, {'dialog_act': '{"general-thank": [["none", "none"]]}', 'metadata': '{}', 'span_info': 
[], 'text': 'thank you so much!'}, {'dialog_act': '{"general-welcome": [["none", "none"]]}', 'metadata': '{"attraction": {"book": {"booked": []}, "semi": {"area": [], "name": [], "type": []}}, "hospital": {"book": {"booked": []}, "semi": {"department": []}}, "hotel": {"book": {"booked": [{"name": ["Everyday Smart Hotel Mayestik"], "reference": "9xvt8m5t"}], "day": ["Minggu"], "people": ["dua"], "stay": ["tujuh"]}, "semi": {"area": [], "internet": ["no"], "name": ["Everyday Smart Hotel Mayestik"], "parking": [], "pricerange": [], "stars": ["2"], "type": []}}, "police": {"book": {"booked": []}, "semi": {}}, "restaurant": {"book": {"booked": [{"name": ["Resto Ngalam"], "reference": "rf00jufq"}], "day": ["Minggu"], "people": ["dua"], "time": ["17:15"]}, "semi": {"area": ["pusat"], "food": ["Asia"], "name": ["Resto Ngalam"], "pricerange": ["harga sedang"]}}, "taxi": {"book": {"booked": []}, "semi": {"arriveBy": [], "departure": [], "destination": [], "leaveAt": []}}, "train": {"book": {"booked": [], "ticket": []}, "semi": {"arriveBy": [], "day": [], "departure": [], "destination": [], "leaveAt": []}}}', 'span_info': [], 'text': "i'm glad to help, you're welcome!"}]}
INFO:__main__:Dataset sample [seacrowd_tod]
{'dialogue_idx': 0, 'dialogue': [{'turn_label': [], 'system_utterance': '', 'turn_idx': 0, 'belief_state': [{'slots': [['food', 'Asia']], 'act': 'inform'}], 'user_utterance': "i'd really like to take my client out to a nice restaurant that serves Asia food.", 'system_acts': [['food']]}, {'turn_label': [], 'system_utterance': 'i show many restaurants that serve Asia food in murah. what area would you like to travel to?', 'turn_idx': 1, 'belief_state': [{'slots': [['pricerange', 'harga sedang']], 'act': 'inform'}, {'slots': [['food', 'Asia']], 'act': 'inform'}, {'slots': [['area', 'pusat']], 'act': 'inform'}], 'user_utterance': 'i am looking 
for an harga sedang Asia restaurant in the area of pusat.', 'system_acts': [['area'], ['food'], ['pricerange']]}, {'turn_label': [], 'system_utterance': 'might i 
recommend Resto Ngalam? that is an harga sedang Asia restaurant in the pusat. i can book a table for you, if you like.', 'turn_idx': 2, 'belief_state': [{'slots': [['bookpeople', 'dua']], 'act': 'inform'}, {'slots': [['booktime', '17:15']], 'act': 'inform'}, {'slots': [['bookday', 'Minggu']], 'act': 'inform'}], 'user_utterance': 'sure thing, please book for dua people at 17:15 on Minggu.', 'system_acts': [['bookday'], ['bookpeople'], ['booktime']]}, {'turn_label': [], 'system_utterance': 'booking was successful. the table will be reserved for 15 minutes. your reference number is : rf00jufq .', 'turn_idx': 3, 'belief_state': [{'slots': [['stars', '2']], 'act': 'inform'}], 'user_utterance': "okay great! thank you so much. could you also help me find a 2 star hotel in the area. i don't need wifi either.", 'system_acts': [['internet'], ['stars']]}, {'turn_label': [], 'system_utterance': 'Everyday Smart Hotel Mayestik is in the selatan and is mahal. it has 2 stars and no internet or parking. would you like to book a room?', 'turn_idx': 4, 'belief_state': [], 'user_utterance': 'that sounds great. please book that now.', 'system_acts': [['internet'], ['parking']]}, {'turn_label': [], 'system_utterance': 'may i ask how many people are in your group?', 'turn_idx': 5, 'belief_state': [{'slots': [['bookpeople', 'dua']], 'act': 'inform'}], 'user_utterance': 'i have dua people in my group.', 'system_acts': [['bookpeople']]}, {'turn_label': [], 'system_utterance': 'how many days would you like to stay?', 'turn_idx': 6, 'belief_state': [{'slots': [['bookstay', 'empat']], 'act': 'inform'}, {'slots': [['bookday', 'Minggu']], 'act': 'inform'}], 'user_utterance': 'empat nights, starting the Minggu as the reservation.', 'system_acts': [['bookday'], ['bookstay']]}, {'turn_label': [], 'system_utterance': "i'm sorry. it looks like they're full. would you like me to look for something else?", 'turn_idx': 7, 'belief_state': [], 'user_utterance': 'yes please. is there something else available in that area?', 'system_acts': []}, {'turn_label': [], 'system_utterance': "i'm sorry, it looks like that is the only 2 star homestay in barat, would you like me to look somewhere else?", 'turn_idx': 8, 'belief_state': [{'slots': [['bookstay', 'tujuh']], 'act': 'inform'}], 'user_utterance': "can we try for tujuh night instead of 2? i'll need the reference number please.", 'system_acts': [['bookstay']]}, {'turn_label': [], 'system_utterance': 'i was able to get lima night, the reference number is 9xvt8m5t .', 'turn_idx': 9, 'belief_state': [], 'user_utterance': 'thank you so much!', 'system_acts': [['none']]}, {'turn_label': [], 'system_utterance': "i'm glad to help, you're welcome!", 'turn_idx': 10, 'belief_state': [], 'user_utterance': '', 'system_acts': []}]}
INFO:__main__:Checking global ID uniqueness
INFO:__main__:Found 0 unique IDs
INFO:__main__:Gathering schema statistics
INFO:__main__:Gathering schema statistics
train
==========
dialogue_idx: 10437
dialogue: 81959

.
----------------------------------------------------------------------
Ran 1 test in 18.155s
```

### CODE REVIEW

**Comment by sabilmakbar** [comment]
> Because this is a local dataset (I have some problems while loading the datasets directly from OneDrive URLs, so I need to download them via this link https://entuedu-my.sharepoint.com/personal/bosheng001_e_ntu_edu_sg/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fbosheng001%5Fe%5Fntu%5Fedu%5Fsg%2FDocuments%2Fglobalwoz%5Fv2&ga=1)

Just throwing a possible workaround. Have you tried to copy the download link? after you click download, supposedly you can obtain it's download link (like this [one](https://entuedu-my.sharepoint.com/personal/bosheng001_e_ntu_edu_sg/_layouts/15/download.aspx?SourceUrl=%2Fpersonal%2Fbosheng001%5Fe%5Fntu%5Fedu%5Fsg%2FDocuments%2Fglobalwoz%5Fv2%2FE%26E%20%28MultiWoZ%202%2E2%29%2FE%26E%20%28MultiWoZ2%2E2%29%2Ejson) and pass it directly to HF Download methods

**Review by sabilmakbar — COMMENTED** [review]
Init review. Won't review the dataloader methods for now prior to having clarity whether it's possible to make it publicly available.

**Comment by dehanalkautsar** [comment]
> Just throwing a possible workaround. Have you tried to copy the download link? after you click download, supposedly you can obtain it's download link (like this [one](https://entuedu-my.sharepoint.com/personal/bosheng001_e_ntu_edu_sg/_layouts/15/download.aspx?SourceUrl=%2Fpersonal%2Fbosheng001%5Fe%5Fntu%5Fedu%5Fsg%2FDocuments%2Fglobalwoz%5Fv2%2FE%26E%20%28MultiWoZ%202%2E2%29%2FE%26E%20%28MultiWoZ2%2E2%29%2Ejson) and pass it directly to HF Download methods

I've got an error like this whenever try to download directly from the link: 
```raise ConnectionError(f"Couldn't reach {url} (error {response.status_code})")
ConnectionError: Couldn't reach https://entuedu-my.sharepoint.com/personal/bosheng001_e_ntu_edu_sg/_layouts/15/download.aspx?SourceUrl=%2Fpersonal%2Fbosheng001%5Fe%5Fntu%5Fedu%5Fsg%2FDocuments%2Fglobalwoz%5Fv2%2FE%26F%2Fid%2FE%26F%5Fid%2Ejson (error 403)

What are your thoughts on this? @sabilmakbar

**Comment by SamuelCahyawijaya** [comment]
@dehanalkautsar : Do you have the local copy of the dataset? If so, would you be able to ask the authors for the license of the dataset? 

Since the dataset is based on MultiWoZv2.2 and MultiWoZv2.2 is licensed as Apache 2.0  (https://huggingface.co/datasets/multi_woz_v22), I expect that GlobalWoZ will also have a similar license. If so, we can redistribute the dataset and make a copy of the dataset on a GitHub repo which will be easier to access.

**Comment by dehanalkautsar** [comment]
> @dehanalkautsar : Do you have the local copy of the dataset? If so, would you be able to ask the authors for the license of the dataset?
> 
> Since the dataset is based on MultiWoZv2.2 and MultiWoZv2.2 is licensed as Apache 2.0 (https://huggingface.co/datasets/multi_woz_v22), I expect that GlobalWoZ will also have a similar license. If so, we can redistribute the dataset and make a copy of the dataset on a GitHub repo which will be easier to access.

I need to download all 9 subset datasets, so far I've downloaded 1 only because of the datasets' size. But for sure that is feasible. I will contact the authors for the license of the dataset.

**Comment by sabilmakbar** [comment]
> I've got an error like this whenever try to download directly from the link:
> 
> raise ConnectionError(f"Couldn't reach {url} (error {response.status_code})")
> ConnectionError: Couldn't reach https://entuedu-my.sharepoint.com/personal/bosheng001_e_ntu_edu_sg/_layouts/15/download.aspx?SourceUrl=%2Fpersonal%2Fbosheng001%5Fe%5Fntu%5Fedu%5Fsg%2FDocuments%2Fglobalwoz%5Fv2%2FE%26F%2Fid%2FE%26F%5Fid%2Ejson (error 403)
> What are your thoughts on this? @sabilmakbar

Hi @dehanalkautsar, it looks like the dataset URL and its JSON download require user authentication. From what I read, it's tricky to pass the Authentication part in order to access and download the data successfully (as you've mentioned previously that you received a `403` response code). Maybe our workaround for now is to pass the local path of downloaded files/folders per language before we can find a way to authenticate the drive via user-email.

**Comment by SamuelCahyawijaya** [comment]
@sabilmakbar  @dehanalkautsar : If the license allows, we can just make a copy of the dataset, put it somewhere else, and link the dataset to the new source link. 

Btw, I saw the email from @dehanalkautsar  to the authors of the dataset, and I think it will be better to email the last author (the supervisor) rather than the main authors (the students).

**Comment by dehanalkautsar** [comment]
> @sabilmakbar @dehanalkautsar : If the license allows, we can just make a copy of the dataset, put it somewhere else, and link the dataset to the new source link.
> 
> Btw, I saw the email from @dehanalkautsar to the authors of the dataset, and I think it will be better to email the last author (the supervisor) rather than the main authors (the students).

Ah okay, I've resent the e-mail to the last author👍

**Comment by dehanalkautsar** [comment]
> Hi @dehanalkautsar , Is there any update on this?

Hi @SamuelCahyawijaya, sadly there is no update as the e-mail hasn't been replied to by either the first or last author.

**Comment by sabilmakbar** [comment]
can we try to test it locally first (by setting it as `_LOCAL=True`) and proceed with the PR before waiting for their permission to copy the data into new sources and modify it slightly (by pointing to new URL and setting `_LOCAL=False`)?

cc @SamuelCahyawijaya

**Comment by holylovenia** [comment]
I'm just passing by to remind @dehanalkautsar to add `__init__.py`.

**Comment by dehanalkautsar** [comment]
@sabilmakbar, I have revised the code according to your earlier feedback. If you have any questions, please feel free to ask. Additionally, for local testing, I've used the following test script:

```
python -m tests.test_seacrowd seacrowd/sea_datasets/globalwoz/globalwoz.py --data_dir=./dataset/globalwoz --subset_id globalwoz_EandF_id
```

The output matches the results from my initial Unit-test output submitted in my first PR.

**Review by SamuelCahyawijaya — APPROVED** [review]
@dehanalkautsar : Thank you for contributing! LGTM!

**Review by sabilmakbar — COMMENTED** [review]
The dataset and unittest looks okay, but do you have the data format for `FandE` and `FandF` ready to be tested similarly (so the implementation is verified for the other two formats), @dehanalkautsar ?

**Comment by dehanalkautsar** [comment]
@sabilmakbar : I have skimmed past the dialogue dataset for the other dataset type (F&E and F&F), and I think the other has a similar data format as E&F as the things that differ in the dialogue can be seen in the picture below: 
image

**Review by sabilmakbar — APPROVED** [review]

**Pull request merged**
