### PR TITLE
Closes #64 | Implement Burmese Name Romanization Dataloader

### LINKED ISSUE #64: Create dataset loader for Myanmar (Burmese) Name Romanization with Alignment on Grapheme-Level
Dataloader name: `burmese_romanize/burmese_romanize.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?burmese_romanize

|     Dataset| burmese_romanize |
|-------------|---|
| Description | This dataset consists of 2,335 Burmese names from real university students and faculty, public figures, and minorities from Myanmar. Each entry includes the original name in Burmese script, its corresponding Romanization, and the aligned Burmese and Latin graphemes. |
| Subsets | - |
| Languages | mya |
| Tasks | Machine Translation |
| License | Creative Commons Attribution Non Commercial Share Alike 4.0 (cc-by-nc-sa-4.0) |
| Homepage | http://www.nlpresearch-ucsy.edu.mm/NLP_UCSY/name-db.html |
| HF URL | - |
| Paper URL | https://att-astrec.nict.go.jp/member/ding/NLP2017-P5-7.pdf |

### PR DESCRIPTION
**Pull request by akhdanfadh**
Closes #64 

### Checkbox
- [x] Confirm that this PR is linked to the dataset issue.
- [x] Create the dataloader script `seacrowd/sea_datasets/my_dataset/my_dataset.py` (please use only lowercase and underscore for dataset naming).
- [x] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [x] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [x] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [x] Confirm dataloader script works with `datasets.load_dataset` function.
- [x] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/<my_dataset>/<my_dataset>.py`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

### CODE REVIEW

**Review by jamesjaya — APPROVED** [review]
tested and lgtm. However, I have a question for the next reviewer or @SamuelCahyawijaya @holylovenia. I don't know how you guys do a transliteration task but I read this paper a bit to understand the `aligned_graphemes` part; I got an impression that `aligned_graphemes` is actually important here and probably we shouldn't omit it. I don't see any of the SEACrowd schemas is suitable here though. Thoughts?

**Comment by holylovenia** [comment]
Sorry for the late reply, @jamesjaya. As discussed with @akhdanfadh @SamuelCahyawijaya @sabilmakbar on Discord #discussion-forum, for now we can ignore the alignment mapping. If we decide to add another schema to cater to this purpose in the future, maybe we can create a task using the `seq_label` schema.

**Review by holylovenia — CHANGES_REQUESTED** [review]
Tried and tested. Works perfectly! I only have a minor change request: could you please add `_LANGUAGES`, @akhdanfadh? Afterwards, I'll merge the dataloader. Thanks for your hardwork!!

**Comment by akhdanfadh** [comment]
It should be okay now; apologies for the delay.

**Review by holylovenia — APPROVED** [review]
No worries! Thank you for the changes and merry christmas, @akhdanfadh! 🎄

**Pull request merged**
