### PR TITLE
Closes #345 | Implemented dataloader for vlsp2016_ner

### LINKED ISSUE #345: Create dataset loader for VLSP2016-NER
Dataloader name: `vlsp2016_ner/vlsp2016_ner.py`
DataCatalogue: http://seacrowd.github.io/seacrowd-catalogue/card.html?vlsp2016_ner

|     Dataset| vlsp2016_ner |
|-------------|---|
| Description | This dataset is collected from electronic newspapers published on the web and provided by VLSP organization. It consists of approximately 15k sentences, each of which contain NE information in the IOB annotation format. |
| Subsets | - |
| Languages | vie |
| Tasks | Named Entiy Recognition |
| License | Creative Commons Attribution Non Commercial 4.0 (cc-by-nc-4.0) |
| Homepage | https://huggingface.co/datasets/datnth1709/VLSP2016-NER-data |
| HF URL | https://huggingface.co/datasets/datnth1709/VLSP2016-NER-data |
| Paper URL | https://drive.google.com/file/d/18FuXxRM0slTeReQUCOj8IiToB5eqVQCT/view |

### PR DESCRIPTION
**Pull request by luckysusanto**
Closes #345 

### Checkbox
- [X] Confirm that this PR is linked to the dataset issue.
- [X] Create the dataloader script `seacrowd/sea_datasets/vlsp2016_ner/vlsp2016_ner.py` (please use only lowercase and underscore for dataset naming).
- [X] Provide values for the `_CITATION`, `_DATASETNAME`, `_DESCRIPTION`, `_HOMEPAGE`, `_LICENSE`, `_URLs`, `_SUPPORTED_TASKS`, `_SOURCE_VERSION`, and `_SEACROWD_VERSION` variables.
- [X] Implement `_info()`, `_split_generators()` and `_generate_examples()` in dataloader script.
- [X] Make sure that the `BUILDER_CONFIGS` class attribute is a list with at least one `SEACrowdConfig` for the source schema and one for a seacrowd schema.
- [X] Confirm dataloader script works with `datasets.load_dataset` function.
- [X] Confirm that your dataloader script passes the test suite run with `python -m tests.test_seacrowd seacrowd/sea_datasets/vlsp2016_ner/vlsp2016_ner.py`.
- [ ] If my dataset is local, I have provided an output of the unit-tests in the PR (please copy paste). This is OPTIONAL for public datasets, as we can test these without access to the data files.

### CODE REVIEW

**Comment by MJonibek** [comment]
@luckysusanto Everything works, only formatting is needed. Can you please run 

make check_file=seacrowd/sea_datasets/vlsp2016_ner/vlsp2016_ner.py

to format the file.

image

To solve three issues from flake8 you need to remove import os, and also add `\` at the end of 17 and 47 lines (descriptions of the dataset) to remove trailing whitespace.

**Review by SamuelCahyawijaya — APPROVED** [review]
@luckysusanto , thanks for implementing the dataset, I don't see any other problem except for the formatting issue mentioned by @MJonibek. I am approving this PR for now and please format the code accordingly to get the other approval.

**Comment by MJonibek** [comment]
@luckysusanto I saw your issue with formatting commands in the discord. I formatted this file myself.

**Comment by MJonibek** [comment]
Merged

**Pull request merged**
